/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: backward                                              *
* Dimensions:  24 * 24                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmbackward;

static GUI_CONST_STORAGE unsigned char _acbackward[] = {
  /* RLE: 024 Pixels @ 000,000 */ 24, 0xFF, 
  /* RLE: 001 Pixels @ 000,001 */ 1, 0xCD, 
  /* RLE: 005 Pixels @ 001,001 */ 5, 0xCB, 
  /* ABS: 002 Pixels @ 006,001 */ 0, 2, 0xD3, 0xFD, 
  /* RLE: 015 Pixels @ 008,001 */ 15, 0xFF, 
  /* ABS: 002 Pixels @ 023,001 */ 0, 2, 0xF1, 0x12, 
  /* RLE: 005 Pixels @ 001,002 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,002 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 013 Pixels @ 008,002 */ 13, 0xFF, 
  /* ABS: 004 Pixels @ 021,002 */ 0, 4, 0xFD, 0xAD, 0x34, 0x12, 
  /* RLE: 005 Pixels @ 001,003 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,003 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 012 Pixels @ 008,003 */ 12, 0xFF, 
  /* ABS: 005 Pixels @ 020,003 */ 0, 5, 0xD3, 0x46, 0x02, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,004 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,004 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 010 Pixels @ 008,004 */ 10, 0xFF, 
  /* ABS: 007 Pixels @ 018,004 */ 0, 7, 0xEB, 0x7A, 0x10, 0x00, 0x00, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,005 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,005 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 008 Pixels @ 008,005 */ 8, 0xFF, 
  /* ABS: 003 Pixels @ 016,005 */ 0, 3, 0xFD, 0xAF, 0x24, 
  /* RLE: 004 Pixels @ 019,005 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 023,005 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,006 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,006 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 007 Pixels @ 008,006 */ 7, 0xFF, 
  /* ABS: 002 Pixels @ 015,006 */ 0, 2, 0xD1, 0x48, 
  /* RLE: 006 Pixels @ 017,006 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 023,006 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,007 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,007 */ 0, 2, 0x26, 0xF1, 
  /* RLE: 005 Pixels @ 008,007 */ 5, 0xFF, 
  /* ABS: 003 Pixels @ 013,007 */ 0, 3, 0xEB, 0x7C, 0x0E, 
  /* RLE: 007 Pixels @ 016,007 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 023,007 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,008 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,008 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 004 Pixels @ 008,008 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 012,008 */ 0, 2, 0xAB, 0x28, 
  /* RLE: 009 Pixels @ 014,008 */ 9, 0x00, 
  /* ABS: 002 Pixels @ 023,008 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,009 */ 5, 0x00, 
  /* ABS: 006 Pixels @ 006,009 */ 0, 6, 0x26, 0xF3, 0xFF, 0xFF, 0xD1, 0x4A, 
  /* RLE: 011 Pixels @ 012,009 */ 11, 0x00, 
  /* ABS: 002 Pixels @ 023,009 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,010 */ 5, 0x00, 
  /* ABS: 005 Pixels @ 006,010 */ 0, 5, 0x26, 0xF1, 0xED, 0x78, 0x10, 
  /* RLE: 012 Pixels @ 011,010 */ 12, 0x00, 
  /* ABS: 002 Pixels @ 023,010 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,011 */ 5, 0x00, 
  /* ABS: 003 Pixels @ 006,011 */ 0, 3, 0x24, 0x9F, 0x28, 
  /* RLE: 014 Pixels @ 009,011 */ 14, 0x00, 
  /* ABS: 002 Pixels @ 023,011 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,012 */ 5, 0x00, 
  /* ABS: 003 Pixels @ 006,012 */ 0, 3, 0x22, 0x89, 0x1A, 
  /* RLE: 014 Pixels @ 009,012 */ 14, 0x00, 
  /* ABS: 002 Pixels @ 023,012 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,013 */ 5, 0x00, 
  /* ABS: 005 Pixels @ 006,013 */ 0, 5, 0x26, 0xF1, 0xE3, 0x60, 0x0A, 
  /* RLE: 012 Pixels @ 011,013 */ 12, 0x00, 
  /* ABS: 002 Pixels @ 023,013 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,014 */ 5, 0x00, 
  /* ABS: 006 Pixels @ 006,014 */ 0, 6, 0x26, 0xF3, 0xFF, 0xFD, 0xBF, 0x34, 
  /* RLE: 011 Pixels @ 012,014 */ 11, 0x00, 
  /* ABS: 002 Pixels @ 023,014 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,015 */ 5, 0x00, 
  /* ABS: 008 Pixels @ 006,015 */ 0, 8, 0x26, 0xF3, 0xFF, 0xFF, 0xFF, 0xFD, 0x93, 0x1A, 
  /* RLE: 009 Pixels @ 014,015 */ 9, 0x00, 
  /* ABS: 002 Pixels @ 023,015 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,016 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,016 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 005 Pixels @ 008,016 */ 5, 0xFF, 
  /* ABS: 003 Pixels @ 013,016 */ 0, 3, 0xE1, 0x64, 0x08, 
  /* RLE: 007 Pixels @ 016,016 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 023,016 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,017 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,017 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 007 Pixels @ 008,017 */ 7, 0xFF, 
  /* ABS: 002 Pixels @ 015,017 */ 0, 2, 0xBF, 0x34, 
  /* RLE: 006 Pixels @ 017,017 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 023,017 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,018 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,018 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 008 Pixels @ 008,018 */ 8, 0xFF, 
  /* ABS: 003 Pixels @ 016,018 */ 0, 3, 0xF9, 0x97, 0x18, 
  /* RLE: 004 Pixels @ 019,018 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 023,018 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,019 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,019 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 010 Pixels @ 008,019 */ 10, 0xFF, 
  /* ABS: 007 Pixels @ 018,019 */ 0, 7, 0xE1, 0x64, 0x08, 0x00, 0x00, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,020 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,020 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 011 Pixels @ 008,020 */ 11, 0xFF, 
  /* ABS: 006 Pixels @ 019,020 */ 0, 6, 0xFD, 0xC1, 0x32, 0x00, 0x0C, 0x12, 
  /* RLE: 005 Pixels @ 001,021 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 006,021 */ 0, 2, 0x26, 0xF3, 
  /* RLE: 013 Pixels @ 008,021 */ 13, 0xFF, 
  /* ABS: 004 Pixels @ 021,021 */ 0, 4, 0xF9, 0x95, 0x26, 0xC1, 
  /* RLE: 005 Pixels @ 001,022 */ 5, 0xBB, 
  /* ABS: 002 Pixels @ 006,022 */ 0, 2, 0xC5, 0xFB, 
  /* RLE: 015 Pixels @ 008,022 */ 15, 0xFF, 
  /* RLE: 001 Pixels @ 023,022 */ 1, 0xE7, 
  /* RLE: 024 Pixels @ 000,023 */ 24, 0xFF, 
  0
};  // 357 bytes for 576 pixels

GUI_CONST_STORAGE GUI_BITMAP bmbackward = {
  24, // xSize
  24, // ySize
  24, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acbackward,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
