/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: close                                                 *
* Dimensions:  24 * 24                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmclose;

static GUI_CONST_STORAGE unsigned char _acclose[] = {
  /* ABS: 007 Pixels @ 000,000 */ 0, 7, 0xFF, 0xF7, 0x9D, 0x3C, 0x22, 0x1E, 0x1C, 
  /* RLE: 004 Pixels @ 007,000 */ 4, 0x1A, 
  /* RLE: 006 Pixels @ 011,000 */ 6, 0x18, 
  /* ABS: 010 Pixels @ 017,000 */ 0, 10, 0x1A, 0x1C, 0x20, 0x3A, 0x9B, 0xF7, 0xFF, 0xF7, 0x5A, 0x02, 
  /* RLE: 018 Pixels @ 003,001 */ 18, 0x00, 
  /* ABS: 005 Pixels @ 021,001 */ 0, 5, 0x02, 0x58, 0xF5, 0x97, 0x02, 
  /* RLE: 020 Pixels @ 002,002 */ 20, 0x00, 
  /* ABS: 003 Pixels @ 022,002 */ 0, 3, 0x02, 0x95, 0x32, 
  /* RLE: 022 Pixels @ 001,003 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,003 */ 0, 2, 0x32, 0x16, 
  /* RLE: 022 Pixels @ 001,004 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,004 */ 0, 2, 0x16, 0x12, 
  /* RLE: 022 Pixels @ 001,005 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,005 */ 0, 2, 0x10, 0x10, 
  /* RLE: 006 Pixels @ 001,006 */ 6, 0x00, 
  /* ABS: 003 Pixels @ 007,006 */ 0, 3, 0x12, 0x52, 0x04, 
  /* RLE: 004 Pixels @ 010,006 */ 4, 0x00, 
  /* ABS: 003 Pixels @ 014,006 */ 0, 3, 0x04, 0x52, 0x12, 
  /* RLE: 006 Pixels @ 017,006 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 023,006 */ 0, 2, 0x0E, 0x0E, 
  /* RLE: 005 Pixels @ 001,007 */ 5, 0x00, 
  /* ABS: 012 Pixels @ 006,007 */ 0, 12, 0x12, 0xBB, 0xFD, 0x8D, 0x08, 0x00, 0x00, 0x06, 0x8D, 0xFD, 0xBB, 0x12, 
  /* RLE: 005 Pixels @ 018,007 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,007 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 005 Pixels @ 001,008 */ 5, 0x00, 
  /* ABS: 012 Pixels @ 006,008 */ 0, 12, 0x5C, 0xFF, 0xFF, 0xFD, 0x8F, 0x04, 0x04, 0x8D, 0xFD, 0xFF, 0xFF, 0x5E, 
  /* RLE: 005 Pixels @ 018,008 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,008 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 005 Pixels @ 001,009 */ 5, 0x00, 
  /* ABS: 012 Pixels @ 006,009 */ 0, 12, 0x06, 0x9F, 0xFF, 0xFF, 0xFD, 0x97, 0x95, 0xFD, 0xFF, 0xFF, 0xA1, 0x06, 
  /* RLE: 005 Pixels @ 018,009 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,009 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 006 Pixels @ 001,010 */ 6, 0x00, 
  /* ABS: 010 Pixels @ 007,010 */ 0, 10, 0x0C, 0x9F, 0xFF, 0xFF, 0xFD, 0xFD, 0xFF, 0xFF, 0xA1, 0x0C, 
  /* RLE: 006 Pixels @ 017,010 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 023,010 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 007 Pixels @ 001,011 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 008,011 */ 0, 2, 0x08, 0xA7, 
  /* RLE: 004 Pixels @ 010,011 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,011 */ 0, 2, 0xA9, 0x08, 
  /* RLE: 007 Pixels @ 016,011 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 023,011 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 007 Pixels @ 001,012 */ 7, 0x00, 
  /* ABS: 008 Pixels @ 008,012 */ 0, 8, 0x04, 0x95, 0xFD, 0xFF, 0xFF, 0xFD, 0x97, 0x04, 
  /* RLE: 007 Pixels @ 016,012 */ 7, 0x00, 
  /* ABS: 002 Pixels @ 023,012 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 006 Pixels @ 001,013 */ 6, 0x00, 
  /* ABS: 003 Pixels @ 007,013 */ 0, 3, 0x06, 0x8D, 0xFD, 
  /* RLE: 004 Pixels @ 010,013 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 014,013 */ 0, 3, 0xFD, 0x8F, 0x08, 
  /* RLE: 006 Pixels @ 017,013 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 023,013 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 005 Pixels @ 001,014 */ 5, 0x00, 
  /* ABS: 012 Pixels @ 006,014 */ 0, 12, 0x04, 0x8D, 0xFD, 0xFF, 0xFF, 0xA9, 0xA7, 0xFF, 0xFF, 0xFD, 0x8D, 0x04, 
  /* RLE: 005 Pixels @ 018,014 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,014 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 005 Pixels @ 001,015 */ 5, 0x00, 
  /* ABS: 012 Pixels @ 006,015 */ 0, 12, 0x5A, 0xFD, 0xFF, 0xFF, 0xA1, 0x08, 0x08, 0x9F, 0xFF, 0xFF, 0xFD, 0x5A, 
  /* RLE: 005 Pixels @ 018,015 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,015 */ 0, 2, 0x0C, 0x0E, 
  /* RLE: 005 Pixels @ 001,016 */ 5, 0x00, 
  /* ABS: 012 Pixels @ 006,016 */ 0, 12, 0x18, 0xC9, 0xFF, 0x9F, 0x0C, 0x00, 0x00, 0x0C, 0x9F, 0xFF, 0xCB, 0x1A, 
  /* RLE: 005 Pixels @ 018,016 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,016 */ 0, 2, 0x0C, 0x10, 
  /* RLE: 006 Pixels @ 001,017 */ 6, 0x00, 
  /* ABS: 003 Pixels @ 007,017 */ 0, 3, 0x1A, 0x68, 0x06, 
  /* RLE: 004 Pixels @ 010,017 */ 4, 0x00, 
  /* ABS: 003 Pixels @ 014,017 */ 0, 3, 0x06, 0x68, 0x1A, 
  /* RLE: 006 Pixels @ 017,017 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 023,017 */ 0, 2, 0x0E, 0x12, 
  /* RLE: 022 Pixels @ 001,018 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,018 */ 0, 2, 0x10, 0x16, 
  /* RLE: 022 Pixels @ 001,019 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,019 */ 0, 2, 0x14, 0x2E, 
  /* RLE: 022 Pixels @ 001,020 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,020 */ 0, 2, 0x2C, 0x8B, 
  /* RLE: 022 Pixels @ 001,021 */ 22, 0x00, 
  /* ABS: 003 Pixels @ 023,021 */ 0, 3, 0x89, 0xF1, 0x48, 
  /* RLE: 020 Pixels @ 002,022 */ 20, 0x00, 
  /* ABS: 006 Pixels @ 022,022 */ 0, 6, 0x48, 0xF1, 0xFF, 0xF1, 0x85, 0x24, 
  /* RLE: 016 Pixels @ 004,023 */ 16, 0x0C, 
  /* ABS: 004 Pixels @ 020,023 */ 0, 4, 0x24, 0x85, 0xF1, 0xFF, 
  0
};  // 350 bytes for 576 pixels

GUI_CONST_STORAGE GUI_BITMAP bmclose = {
  24, // xSize
  24, // ySize
  24, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acclose,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
