/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: forward                                               *
* Dimensions:  24 * 24                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmforward;

static GUI_CONST_STORAGE unsigned char _acforward[] = {
  /* RLE: 024 Pixels @ 000,000 */ 24, 0xFF, 
  /* RLE: 001 Pixels @ 000,001 */ 1, 0xEF, 
  /* RLE: 015 Pixels @ 001,001 */ 15, 0xFF, 
  /* ABS: 002 Pixels @ 016,001 */ 0, 2, 0xFD, 0xD3, 
  /* RLE: 005 Pixels @ 018,001 */ 5, 0xCB, 
  /* ABS: 004 Pixels @ 023,001 */ 0, 4, 0xCD, 0x34, 0xA5, 0xFD, 
  /* RLE: 013 Pixels @ 003,002 */ 13, 0xFF, 
  /* ABS: 002 Pixels @ 016,002 */ 0, 2, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,002 */ 5, 0x00, 
  /* ABS: 005 Pixels @ 023,002 */ 0, 5, 0x0C, 0x12, 0x00, 0x40, 0xCF, 
  /* RLE: 012 Pixels @ 004,003 */ 12, 0xFF, 
  /* ABS: 002 Pixels @ 016,003 */ 0, 2, 0xF7, 0x2E, 
  /* RLE: 005 Pixels @ 018,003 */ 5, 0x00, 
  /* ABS: 007 Pixels @ 023,003 */ 0, 7, 0x0C, 0x12, 0x00, 0x00, 0x0C, 0x72, 0xE9, 
  /* RLE: 010 Pixels @ 006,004 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 016,004 */ 0, 2, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,004 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,004 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 004 Pixels @ 001,005 */ 4, 0x00, 
  /* ABS: 003 Pixels @ 005,005 */ 0, 3, 0x20, 0xA9, 0xFD, 
  /* RLE: 008 Pixels @ 008,005 */ 8, 0xFF, 
  /* ABS: 002 Pixels @ 016,005 */ 0, 2, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,005 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,005 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 006 Pixels @ 001,006 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 007,006 */ 0, 2, 0x42, 0xCB, 
  /* RLE: 007 Pixels @ 009,006 */ 7, 0xFF, 
  /* ABS: 002 Pixels @ 016,006 */ 0, 2, 0xF7, 0x2E, 
  /* RLE: 005 Pixels @ 018,006 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,006 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 007 Pixels @ 001,007 */ 7, 0x00, 
  /* ABS: 003 Pixels @ 008,007 */ 0, 3, 0x0C, 0x74, 0xE9, 
  /* RLE: 005 Pixels @ 011,007 */ 5, 0xFF, 
  /* ABS: 002 Pixels @ 016,007 */ 0, 2, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,007 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,007 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 009 Pixels @ 001,008 */ 9, 0x00, 
  /* ABS: 002 Pixels @ 010,008 */ 0, 2, 0x24, 0xA3, 
  /* RLE: 004 Pixels @ 012,008 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 016,008 */ 0, 2, 0xF7, 0x2E, 
  /* RLE: 005 Pixels @ 018,008 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,008 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 011 Pixels @ 001,009 */ 11, 0x00, 
  /* ABS: 006 Pixels @ 012,009 */ 0, 6, 0x42, 0xCB, 0xFF, 0xFF, 0xF7, 0x2E, 
  /* RLE: 005 Pixels @ 018,009 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,009 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 012 Pixels @ 001,010 */ 12, 0x00, 
  /* ABS: 005 Pixels @ 013,010 */ 0, 5, 0x0E, 0x70, 0xEB, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,010 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,010 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 014 Pixels @ 001,011 */ 14, 0x00, 
  /* ABS: 003 Pixels @ 015,011 */ 0, 3, 0x22, 0x9D, 0x2C, 
  /* RLE: 005 Pixels @ 018,011 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,011 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 014 Pixels @ 001,012 */ 14, 0x00, 
  /* ABS: 003 Pixels @ 015,012 */ 0, 3, 0x16, 0x85, 0x28, 
  /* RLE: 005 Pixels @ 018,012 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,012 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 012 Pixels @ 001,013 */ 12, 0x00, 
  /* ABS: 005 Pixels @ 013,013 */ 0, 5, 0x08, 0x5A, 0xDF, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,013 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,013 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 011 Pixels @ 001,014 */ 11, 0x00, 
  /* ABS: 006 Pixels @ 012,014 */ 0, 6, 0x2E, 0xB9, 0xFD, 0xFF, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,014 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,014 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 009 Pixels @ 001,015 */ 9, 0x00, 
  /* ABS: 008 Pixels @ 010,015 */ 0, 8, 0x16, 0x8B, 0xFB, 0xFF, 0xFF, 0xFF, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,015 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,015 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 007 Pixels @ 001,016 */ 7, 0x00, 
  /* ABS: 003 Pixels @ 008,016 */ 0, 3, 0x06, 0x5E, 0xDD, 
  /* RLE: 005 Pixels @ 011,016 */ 5, 0xFF, 
  /* ABS: 002 Pixels @ 016,016 */ 0, 2, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,016 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,016 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 006 Pixels @ 001,017 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 007,017 */ 0, 2, 0x2E, 0xB7, 
  /* RLE: 007 Pixels @ 009,017 */ 7, 0xFF, 
  /* ABS: 002 Pixels @ 016,017 */ 0, 2, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,017 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,017 */ 0, 2, 0x0C, 0x12, 
  /* RLE: 004 Pixels @ 001,018 */ 4, 0x00, 
  /* ABS: 003 Pixels @ 005,018 */ 0, 3, 0x14, 0x91, 0xF9, 
  /* RLE: 008 Pixels @ 008,018 */ 8, 0xFF, 
  /* ABS: 002 Pixels @ 016,018 */ 0, 2, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,018 */ 5, 0x00, 
  /* ABS: 007 Pixels @ 023,018 */ 0, 7, 0x0C, 0x12, 0x00, 0x00, 0x08, 0x5C, 0xDD, 
  /* RLE: 010 Pixels @ 006,019 */ 10, 0xFF, 
  /* ABS: 002 Pixels @ 016,019 */ 0, 2, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,019 */ 5, 0x00, 
  /* ABS: 006 Pixels @ 023,019 */ 0, 6, 0x0C, 0x12, 0x00, 0x2C, 0xBB, 0xFD, 
  /* RLE: 011 Pixels @ 005,020 */ 11, 0xFF, 
  /* ABS: 002 Pixels @ 016,020 */ 0, 2, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,020 */ 5, 0x00, 
  /* ABS: 004 Pixels @ 023,020 */ 0, 4, 0x0C, 0x28, 0x8F, 0xF9, 
  /* RLE: 013 Pixels @ 003,021 */ 13, 0xFF, 
  /* ABS: 002 Pixels @ 016,021 */ 0, 2, 0xF5, 0x2E, 
  /* RLE: 005 Pixels @ 018,021 */ 5, 0x00, 
  /* ABS: 002 Pixels @ 023,021 */ 0, 2, 0x0C, 0xE5, 
  /* RLE: 015 Pixels @ 001,022 */ 15, 0xFF, 
  /* ABS: 002 Pixels @ 016,022 */ 0, 2, 0xFD, 0xC7, 
  /* RLE: 005 Pixels @ 018,022 */ 5, 0xBB, 
  /* RLE: 001 Pixels @ 023,022 */ 1, 0xBF, 
  /* RLE: 024 Pixels @ 000,023 */ 24, 0xFF, 
  0
};  // 357 bytes for 576 pixels

GUI_CONST_STORAGE GUI_BITMAP bmforward = {
  24, // xSize
  24, // ySize
  24, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acforward,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
