/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: led                                                   *
* Dimensions:  48 * 48                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmled;

static GUI_CONST_STORAGE unsigned char _acled[] = {
  /* RLE: 018 Pixels @ 000,000 */ 18, 0xFF, 
  /* ABS: 012 Pixels @ 018,000 */ 0, 12, 0xEF, 0xCD, 0x9D, 0x58, 0x34, 0x1E, 0x1E, 0x34, 0x58, 0x9B, 0xCD, 0xEF, 
  /* RLE: 034 Pixels @ 030,000 */ 34, 0xFF, 
  /* ABS: 005 Pixels @ 016,001 */ 0, 5, 0xFB, 0xC3, 0x62, 0x20, 0x02, 
  /* RLE: 006 Pixels @ 021,001 */ 6, 0x00, 
  /* ABS: 005 Pixels @ 027,001 */ 0, 5, 0x02, 0x20, 0x62, 0xC5, 0xFB, 
  /* RLE: 031 Pixels @ 032,001 */ 31, 0xFF, 
  /* ABS: 003 Pixels @ 015,002 */ 0, 3, 0xF3, 0x8D, 0x26, 
  /* RLE: 012 Pixels @ 018,002 */ 12, 0x00, 
  /* ABS: 003 Pixels @ 030,002 */ 0, 3, 0x28, 0x8F, 0xF3, 
  /* RLE: 029 Pixels @ 033,002 */ 29, 0xFF, 
  /* ABS: 020 Pixels @ 014,003 */ 0, 20, 0xEB, 0x56, 0x02, 0x00, 0x00, 0x00, 0x04, 0x1E, 0x30, 0x3A, 0x3A, 0x30, 0x20, 0x06, 0x00, 0x00, 0x00, 0x02, 0x56, 0xEB, 
  /* RLE: 027 Pixels @ 034,003 */ 27, 0xFF, 
  /* ABS: 022 Pixels @ 013,004 */ 0, 22, 0xEB, 0x6E, 0x00, 0x00, 0x00, 0x04, 0x2E, 0x7A, 0xBD, 0xDF, 0xF3, 0xF3, 0xE1, 0xC1, 0x7E, 0x30, 0x04, 0x00, 0x00, 0x00, 0x6E, 0xEB, 
  /* RLE: 025 Pixels @ 035,004 */ 25, 0xFF, 
  /* ABS: 009 Pixels @ 012,005 */ 0, 9, 0xF9, 0x91, 0x0E, 0x00, 0x00, 0x00, 0x5E, 0xD1, 0xF7, 
  /* RLE: 006 Pixels @ 021,005 */ 6, 0xFF, 
  /* ABS: 009 Pixels @ 027,005 */ 0, 9, 0xF9, 0xD3, 0x60, 0x00, 0x00, 0x00, 0x0E, 0x8F, 0xF9, 
  /* RLE: 024 Pixels @ 036,005 */ 24, 0xFF, 
  /* ABS: 006 Pixels @ 012,006 */ 0, 6, 0xC3, 0x1E, 0x00, 0x00, 0x0C, 0x78, 
  /* RLE: 011 Pixels @ 018,006 */ 11, 0xFF, 
  /* ABS: 007 Pixels @ 029,006 */ 0, 7, 0xFD, 0x78, 0x0C, 0x00, 0x00, 0x1A, 0xBF, 
  /* RLE: 024 Pixels @ 036,006 */ 24, 0xFF, 
  /* ABS: 006 Pixels @ 012,007 */ 0, 6, 0x64, 0x00, 0x00, 0x06, 0x62, 0xEB, 
  /* RLE: 012 Pixels @ 018,007 */ 12, 0xFF, 
  /* ABS: 006 Pixels @ 030,007 */ 0, 6, 0xEB, 0x62, 0x06, 0x00, 0x00, 0x5C, 
  /* RLE: 023 Pixels @ 036,007 */ 23, 0xFF, 
  /* ABS: 006 Pixels @ 011,008 */ 0, 6, 0xED, 0x0E, 0x00, 0x00, 0x26, 0xCB, 
  /* RLE: 014 Pixels @ 017,008 */ 14, 0xFF, 
  /* ABS: 006 Pixels @ 031,008 */ 0, 6, 0xCD, 0x26, 0x00, 0x00, 0x0E, 0xE9, 
  /* RLE: 022 Pixels @ 037,008 */ 22, 0xFF, 
  /* ABS: 005 Pixels @ 011,009 */ 0, 5, 0x9B, 0x00, 0x00, 0x00, 0x85, 
  /* RLE: 016 Pixels @ 016,009 */ 16, 0xFF, 
  /* ABS: 005 Pixels @ 032,009 */ 0, 5, 0x87, 0x00, 0x00, 0x00, 0x99, 
  /* RLE: 022 Pixels @ 037,009 */ 22, 0xFF, 
  /* ABS: 005 Pixels @ 011,010 */ 0, 5, 0x5E, 0x00, 0x00, 0x00, 0xDB, 
  /* RLE: 016 Pixels @ 016,010 */ 16, 0xFF, 
  /* ABS: 005 Pixels @ 032,010 */ 0, 5, 0xDB, 0x00, 0x00, 0x00, 0x5E, 
  /* RLE: 021 Pixels @ 037,010 */ 21, 0xFF, 
  /* ABS: 006 Pixels @ 010,011 */ 0, 6, 0xFB, 0x40, 0x00, 0x00, 0x0A, 0xFD, 
  /* RLE: 016 Pixels @ 016,011 */ 16, 0xFF, 
  /* ABS: 006 Pixels @ 032,011 */ 0, 6, 0xFD, 0x0A, 0x00, 0x00, 0x40, 0xF9, 
  /* RLE: 020 Pixels @ 038,011 */ 20, 0xFF, 
  /* ABS: 005 Pixels @ 010,012 */ 0, 5, 0xF3, 0x3A, 0x00, 0x00, 0x18, 
  /* RLE: 018 Pixels @ 015,012 */ 18, 0xFF, 
  /* ABS: 005 Pixels @ 033,012 */ 0, 5, 0x1A, 0x00, 0x00, 0x38, 0xF1, 
  /* RLE: 020 Pixels @ 038,012 */ 20, 0xFF, 
  /* ABS: 005 Pixels @ 010,013 */ 0, 5, 0xEF, 0x38, 0x00, 0x00, 0x1C, 
  /* RLE: 018 Pixels @ 015,013 */ 18, 0xFF, 
  /* ABS: 005 Pixels @ 033,013 */ 0, 5, 0x1E, 0x00, 0x00, 0x38, 0xEF, 
  /* RLE: 020 Pixels @ 038,013 */ 20, 0xFF, 
  /* ABS: 005 Pixels @ 010,014 */ 0, 5, 0xED, 0x36, 0x00, 0x00, 0x20, 
  /* RLE: 018 Pixels @ 015,014 */ 18, 0xFF, 
  /* ABS: 005 Pixels @ 033,014 */ 0, 5, 0x22, 0x00, 0x00, 0x36, 0xED, 
  /* RLE: 020 Pixels @ 038,014 */ 20, 0xFF, 
  /* ABS: 005 Pixels @ 010,015 */ 0, 5, 0xEB, 0x36, 0x00, 0x00, 0x22, 
  /* RLE: 018 Pixels @ 015,015 */ 18, 0xFF, 
  /* ABS: 005 Pixels @ 033,015 */ 0, 5, 0x24, 0x00, 0x00, 0x34, 0xE9, 
  /* RLE: 020 Pixels @ 038,015 */ 20, 0xFF, 
  /* ABS: 005 Pixels @ 010,016 */ 0, 5, 0xE9, 0x34, 0x00, 0x00, 0x24, 
  /* RLE: 018 Pixels @ 015,016 */ 18, 0xFF, 
  /* ABS: 005 Pixels @ 033,016 */ 0, 5, 0x26, 0x00, 0x00, 0x34, 0xE9, 
  /* RLE: 020 Pixels @ 038,016 */ 20, 0xFF, 
  /* ABS: 005 Pixels @ 010,017 */ 0, 5, 0xE9, 0x34, 0x00, 0x00, 0x26, 
  /* RLE: 018 Pixels @ 015,017 */ 18, 0xFF, 
  /* ABS: 005 Pixels @ 033,017 */ 0, 5, 0x28, 0x00, 0x00, 0x34, 0xE7, 
  /* RLE: 020 Pixels @ 038,017 */ 20, 0xFF, 
  /* ABS: 005 Pixels @ 010,018 */ 0, 5, 0xE5, 0x32, 0x00, 0x00, 0x28, 
  /* RLE: 018 Pixels @ 015,018 */ 18, 0xFF, 
  /* ABS: 005 Pixels @ 033,018 */ 0, 5, 0x2A, 0x00, 0x00, 0x32, 0xE5, 
  /* RLE: 020 Pixels @ 038,018 */ 20, 0xFF, 
  /* ABS: 005 Pixels @ 010,019 */ 0, 5, 0xE5, 0x32, 0x00, 0x00, 0x2A, 
  /* RLE: 018 Pixels @ 015,019 */ 18, 0xFF, 
  /* ABS: 005 Pixels @ 033,019 */ 0, 5, 0x2C, 0x00, 0x00, 0x32, 0xE3, 
  /* RLE: 017 Pixels @ 038,019 */ 17, 0xFF, 
  /* ABS: 008 Pixels @ 007,020 */ 0, 8, 0xF3, 0x9B, 0x64, 0x54, 0x12, 0x00, 0x00, 0x0E, 
  /* RLE: 018 Pixels @ 015,020 */ 18, 0x5E, 
  /* ABS: 008 Pixels @ 033,020 */ 0, 8, 0x10, 0x00, 0x00, 0x12, 0x54, 0x64, 0x99, 0xF3, 
  /* RLE: 014 Pixels @ 041,020 */ 14, 0xFF, 
  /* ABS: 002 Pixels @ 007,021 */ 0, 2, 0x95, 0x0A, 
  /* RLE: 030 Pixels @ 009,021 */ 30, 0x00, 
  /* ABS: 002 Pixels @ 039,021 */ 0, 2, 0x0A, 0x93, 
  /* RLE: 014 Pixels @ 041,021 */ 14, 0xFF, 
  /* ABS: 002 Pixels @ 007,022 */ 0, 2, 0x83, 0x02, 
  /* RLE: 031 Pixels @ 009,022 */ 31, 0x00, 
  /* RLE: 001 Pixels @ 040,022 */ 1, 0x81, 
  /* RLE: 014 Pixels @ 041,022 */ 14, 0xFF, 
  /* RLE: 001 Pixels @ 007,023 */ 1, 0x81, 
  /* RLE: 032 Pixels @ 008,023 */ 32, 0x00, 
  /* RLE: 001 Pixels @ 040,023 */ 1, 0x81, 
  /* RLE: 014 Pixels @ 041,023 */ 14, 0xFF, 
  /* RLE: 001 Pixels @ 007,024 */ 1, 0x81, 
  /* RLE: 032 Pixels @ 008,024 */ 32, 0x00, 
  /* RLE: 001 Pixels @ 040,024 */ 1, 0x81, 
  /* RLE: 014 Pixels @ 041,024 */ 14, 0xFF, 
  /* ABS: 002 Pixels @ 007,025 */ 0, 2, 0x83, 0x02, 
  /* RLE: 031 Pixels @ 009,025 */ 31, 0x00, 
  /* RLE: 001 Pixels @ 040,025 */ 1, 0x81, 
  /* RLE: 014 Pixels @ 041,025 */ 14, 0xFF, 
  /* ABS: 002 Pixels @ 007,026 */ 0, 2, 0x93, 0x0A, 
  /* RLE: 030 Pixels @ 009,026 */ 30, 0x00, 
  /* ABS: 002 Pixels @ 039,026 */ 0, 2, 0x08, 0x91, 
  /* RLE: 014 Pixels @ 041,026 */ 14, 0xFF, 
  /* ABS: 002 Pixels @ 007,027 */ 0, 2, 0xF3, 0x91, 
  /* RLE: 030 Pixels @ 009,027 */ 30, 0x64, 
  /* ABS: 002 Pixels @ 039,027 */ 0, 2, 0x8F, 0xF1, 
  /* RLE: 071 Pixels @ 041,027 */ 71, 0xFF, 
  /* ABS: 005 Pixels @ 016,029 */ 0, 5, 0xCD, 0x8B, 0x87, 0x87, 0xD3, 
  /* RLE: 006 Pixels @ 021,029 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,029 */ 0, 5, 0xD5, 0x87, 0x87, 0x8B, 0xCD, 
  /* RLE: 032 Pixels @ 032,029 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,030 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,030 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,030 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,030 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,031 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,031 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,031 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,031 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,032 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,032 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,032 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,032 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,033 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,033 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,033 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,033 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,034 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,034 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,034 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,034 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,035 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,035 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,035 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,035 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,036 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,036 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,036 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,036 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,037 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,037 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,037 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,037 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,038 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,038 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,038 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,038 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,039 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,039 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,039 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,039 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,040 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,040 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,040 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,040 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,041 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,041 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,041 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,041 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,042 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,042 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,042 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,042 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,043 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,043 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,043 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,043 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,044 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,044 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,044 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,044 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,045 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,045 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,045 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,045 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,046 */ 0, 5, 0x95, 0x0A, 0x00, 0x00, 0xA5, 
  /* RLE: 006 Pixels @ 021,046 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,046 */ 0, 5, 0xA5, 0x00, 0x00, 0x0A, 0x93, 
  /* RLE: 032 Pixels @ 032,046 */ 32, 0xFF, 
  /* ABS: 005 Pixels @ 016,047 */ 0, 5, 0x9F, 0x22, 0x18, 0x18, 0xAD, 
  /* RLE: 006 Pixels @ 021,047 */ 6, 0xFF, 
  /* ABS: 005 Pixels @ 027,047 */ 0, 5, 0xAF, 0x18, 0x18, 0x20, 0x9D, 
  /* RLE: 016 Pixels @ 032,047 */ 16, 0xFF, 
  0
};  // 825 bytes for 2304 pixels

GUI_CONST_STORAGE GUI_BITMAP bmled = {
  48, // xSize
  48, // ySize
  48, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acled,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
