/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: pause                                                 *
* Dimensions:  24 * 24                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmpause;

static GUI_CONST_STORAGE unsigned char _acpause[] = {
  /* ABS: 009 Pixels @ 000,000 */ 0, 9, 0xFF, 0xE5, 0x40, 0x10, 0x0E, 0x0E, 0x10, 0x18, 0x7E, 
  /* RLE: 006 Pixels @ 009,000 */ 6, 0xFF, 
  /* ABS: 011 Pixels @ 015,000 */ 0, 11, 0x89, 0x18, 0x0E, 0x0E, 0x0E, 0x12, 0x38, 0xDD, 0xFF, 0xFF, 0x9F, 
  /* RLE: 006 Pixels @ 002,001 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 008,001 */ 0, 2, 0x06, 0xFD, 
  /* RLE: 005 Pixels @ 010,001 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,001 */ 1, 0x12, 
  /* RLE: 006 Pixels @ 016,001 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,001 */ 0, 4, 0x93, 0xFF, 0xFF, 0x97, 
  /* RLE: 007 Pixels @ 002,002 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,002 */ 1, 0xF9, 
  /* RLE: 005 Pixels @ 010,002 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,002 */ 1, 0x08, 
  /* RLE: 006 Pixels @ 016,002 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,002 */ 0, 4, 0x8B, 0xFF, 0xFF, 0x93, 
  /* RLE: 007 Pixels @ 002,003 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,003 */ 1, 0xF7, 
  /* RLE: 005 Pixels @ 010,003 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,003 */ 1, 0x06, 
  /* RLE: 006 Pixels @ 016,003 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,003 */ 0, 4, 0x87, 0xFF, 0xFF, 0x93, 
  /* RLE: 007 Pixels @ 002,004 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,004 */ 1, 0xF5, 
  /* RLE: 005 Pixels @ 010,004 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,004 */ 1, 0x04, 
  /* RLE: 006 Pixels @ 016,004 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,004 */ 0, 4, 0x85, 0xFF, 0xFF, 0x91, 
  /* RLE: 007 Pixels @ 002,005 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,005 */ 1, 0xF3, 
  /* RLE: 005 Pixels @ 010,005 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,005 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 016,005 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,005 */ 0, 4, 0x83, 0xFF, 0xFF, 0x8F, 
  /* RLE: 007 Pixels @ 002,006 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,006 */ 1, 0xF3, 
  /* RLE: 004 Pixels @ 010,006 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,006 */ 0, 2, 0xFD, 0x02, 
  /* RLE: 006 Pixels @ 016,006 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,006 */ 0, 4, 0x81, 0xFF, 0xFF, 0x8D, 
  /* RLE: 007 Pixels @ 002,007 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,007 */ 1, 0xF1, 
  /* RLE: 004 Pixels @ 010,007 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,007 */ 0, 2, 0xFD, 0x02, 
  /* RLE: 006 Pixels @ 016,007 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,007 */ 0, 4, 0x81, 0xFF, 0xFF, 0x8D, 
  /* RLE: 007 Pixels @ 002,008 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,008 */ 1, 0xF1, 
  /* RLE: 004 Pixels @ 010,008 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,008 */ 0, 2, 0xFB, 0x02, 
  /* RLE: 006 Pixels @ 016,008 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,008 */ 0, 4, 0x81, 0xFF, 0xFF, 0x8D, 
  /* RLE: 007 Pixels @ 002,009 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,009 */ 1, 0xF1, 
  /* RLE: 004 Pixels @ 010,009 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,009 */ 0, 2, 0xFB, 0x02, 
  /* RLE: 006 Pixels @ 016,009 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,009 */ 0, 4, 0x7E, 0xFF, 0xFF, 0x8D, 
  /* RLE: 007 Pixels @ 002,010 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,010 */ 1, 0xEF, 
  /* RLE: 004 Pixels @ 010,010 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,010 */ 0, 2, 0xFB, 0x02, 
  /* RLE: 006 Pixels @ 016,010 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,010 */ 0, 4, 0x7E, 0xFF, 0xFF, 0x8D, 
  /* RLE: 007 Pixels @ 002,011 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,011 */ 1, 0xEF, 
  /* RLE: 004 Pixels @ 010,011 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,011 */ 0, 2, 0xFB, 0x02, 
  /* RLE: 006 Pixels @ 016,011 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,011 */ 0, 4, 0x81, 0xFF, 0xFF, 0x8D, 
  /* RLE: 007 Pixels @ 002,012 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,012 */ 1, 0xEF, 
  /* RLE: 004 Pixels @ 010,012 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,012 */ 0, 2, 0xFB, 0x02, 
  /* RLE: 006 Pixels @ 016,012 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,012 */ 0, 4, 0x7E, 0xFF, 0xFF, 0x8D, 
  /* RLE: 007 Pixels @ 002,013 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,013 */ 1, 0xEF, 
  /* RLE: 004 Pixels @ 010,013 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,013 */ 0, 2, 0xFB, 0x02, 
  /* RLE: 006 Pixels @ 016,013 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,013 */ 0, 4, 0x81, 0xFF, 0xFF, 0x8D, 
  /* RLE: 007 Pixels @ 002,014 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,014 */ 1, 0xF1, 
  /* RLE: 004 Pixels @ 010,014 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,014 */ 0, 2, 0xFB, 0x02, 
  /* RLE: 006 Pixels @ 016,014 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,014 */ 0, 4, 0x81, 0xFF, 0xFF, 0x8D, 
  /* RLE: 007 Pixels @ 002,015 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,015 */ 1, 0xF1, 
  /* RLE: 004 Pixels @ 010,015 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,015 */ 0, 2, 0xFD, 0x02, 
  /* RLE: 006 Pixels @ 016,015 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,015 */ 0, 4, 0x7E, 0xFF, 0xFF, 0x8D, 
  /* RLE: 007 Pixels @ 002,016 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,016 */ 1, 0xF1, 
  /* RLE: 004 Pixels @ 010,016 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,016 */ 0, 2, 0xFD, 0x02, 
  /* RLE: 006 Pixels @ 016,016 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,016 */ 0, 4, 0x81, 0xFF, 0xFF, 0x8F, 
  /* RLE: 007 Pixels @ 002,017 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,017 */ 1, 0xF3, 
  /* RLE: 004 Pixels @ 010,017 */ 4, 0xFF, 
  /* ABS: 002 Pixels @ 014,017 */ 0, 2, 0xFD, 0x02, 
  /* RLE: 006 Pixels @ 016,017 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,017 */ 0, 4, 0x81, 0xFF, 0xFF, 0x91, 
  /* RLE: 007 Pixels @ 002,018 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,018 */ 1, 0xF3, 
  /* RLE: 005 Pixels @ 010,018 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,018 */ 1, 0x02, 
  /* RLE: 006 Pixels @ 016,018 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,018 */ 0, 4, 0x83, 0xFF, 0xFF, 0x93, 
  /* RLE: 007 Pixels @ 002,019 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,019 */ 1, 0xF5, 
  /* RLE: 005 Pixels @ 010,019 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,019 */ 1, 0x04, 
  /* RLE: 006 Pixels @ 016,019 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,019 */ 0, 4, 0x85, 0xFF, 0xFF, 0x93, 
  /* RLE: 007 Pixels @ 002,020 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,020 */ 1, 0xF7, 
  /* RLE: 005 Pixels @ 010,020 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,020 */ 1, 0x06, 
  /* RLE: 006 Pixels @ 016,020 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,020 */ 0, 4, 0x87, 0xFF, 0xFF, 0x97, 
  /* RLE: 007 Pixels @ 002,021 */ 7, 0x00, 
  /* RLE: 001 Pixels @ 009,021 */ 1, 0xF9, 
  /* RLE: 005 Pixels @ 010,021 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,021 */ 1, 0x08, 
  /* RLE: 006 Pixels @ 016,021 */ 6, 0x00, 
  /* ABS: 004 Pixels @ 022,021 */ 0, 4, 0x89, 0xFF, 0xFF, 0x9F, 
  /* RLE: 006 Pixels @ 002,022 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 008,022 */ 0, 2, 0x04, 0xFD, 
  /* RLE: 005 Pixels @ 010,022 */ 5, 0xFF, 
  /* RLE: 001 Pixels @ 015,022 */ 1, 0x10, 
  /* RLE: 006 Pixels @ 016,022 */ 6, 0x00, 
  /* ABS: 005 Pixels @ 022,022 */ 0, 5, 0x91, 0xFF, 0xFF, 0xE1, 0x32, 
  /* RLE: 004 Pixels @ 003,023 */ 4, 0x0C, 
  /* ABS: 002 Pixels @ 007,023 */ 0, 2, 0x0E, 0x72, 
  /* RLE: 006 Pixels @ 009,023 */ 6, 0xFF, 
  /* ABS: 002 Pixels @ 015,023 */ 0, 2, 0x7C, 0x10, 
  /* RLE: 004 Pixels @ 017,023 */ 4, 0x0C, 
  /* ABS: 003 Pixels @ 021,023 */ 0, 3, 0x2C, 0xDB, 0xFF, 
  0
};  // 426 bytes for 576 pixels

GUI_CONST_STORAGE GUI_BITMAP bmpause = {
  24, // xSize
  24, // ySize
  24, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acpause,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
