/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: play                                                  *
* Dimensions:  24 * 24                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmplay;

static GUI_CONST_STORAGE unsigned char _acplay[] = {
  /* ABS: 006 Pixels @ 000,000 */ 0, 6, 0xFF, 0xCB, 0x1E, 0x42, 0xBF, 0xFD, 
  /* RLE: 019 Pixels @ 006,000 */ 19, 0xFF, 
  /* ABS: 006 Pixels @ 001,001 */ 0, 6, 0x83, 0x00, 0x00, 0x08, 0x5C, 0xDF, 
  /* RLE: 018 Pixels @ 007,001 */ 18, 0xFF, 
  /* RLE: 001 Pixels @ 001,002 */ 1, 0x7C, 
  /* RLE: 004 Pixels @ 002,002 */ 4, 0x00, 
  /* ABS: 003 Pixels @ 006,002 */ 0, 3, 0x16, 0x87, 0xF5, 
  /* RLE: 016 Pixels @ 009,002 */ 16, 0xFF, 
  /* RLE: 001 Pixels @ 001,003 */ 1, 0x7A, 
  /* RLE: 006 Pixels @ 002,003 */ 6, 0x00, 
  /* ABS: 003 Pixels @ 008,003 */ 0, 3, 0x24, 0xAF, 0xFB, 
  /* RLE: 014 Pixels @ 011,003 */ 14, 0xFF, 
  /* RLE: 001 Pixels @ 001,004 */ 1, 0x78, 
  /* RLE: 007 Pixels @ 002,004 */ 7, 0x00, 
  /* ABS: 003 Pixels @ 009,004 */ 0, 3, 0x04, 0x4A, 0xCD, 
  /* RLE: 013 Pixels @ 012,004 */ 13, 0xFF, 
  /* RLE: 001 Pixels @ 001,005 */ 1, 0x76, 
  /* RLE: 009 Pixels @ 002,005 */ 9, 0x00, 
  /* ABS: 003 Pixels @ 011,005 */ 0, 3, 0x0A, 0x72, 0xED, 
  /* RLE: 011 Pixels @ 014,005 */ 11, 0xFF, 
  /* RLE: 001 Pixels @ 001,006 */ 1, 0x76, 
  /* RLE: 011 Pixels @ 002,006 */ 11, 0x00, 
  /* ABS: 003 Pixels @ 013,006 */ 0, 3, 0x18, 0x95, 0xF7, 
  /* RLE: 009 Pixels @ 016,006 */ 9, 0xFF, 
  /* RLE: 001 Pixels @ 001,007 */ 1, 0x76, 
  /* RLE: 012 Pixels @ 002,007 */ 12, 0x00, 
  /* ABS: 004 Pixels @ 014,007 */ 0, 4, 0x02, 0x38, 0xBD, 0xFB, 
  /* RLE: 007 Pixels @ 018,007 */ 7, 0xFF, 
  /* RLE: 001 Pixels @ 001,008 */ 1, 0x76, 
  /* RLE: 014 Pixels @ 002,008 */ 14, 0x00, 
  /* ABS: 003 Pixels @ 016,008 */ 0, 3, 0x06, 0x58, 0xE1, 
  /* RLE: 006 Pixels @ 019,008 */ 6, 0xFF, 
  /* RLE: 001 Pixels @ 001,009 */ 1, 0x76, 
  /* RLE: 016 Pixels @ 002,009 */ 16, 0x00, 
  /* ABS: 003 Pixels @ 018,009 */ 0, 3, 0x0C, 0x7E, 0xED, 
  /* RLE: 004 Pixels @ 021,009 */ 4, 0xFF, 
  /* RLE: 001 Pixels @ 001,010 */ 1, 0x74, 
  /* RLE: 018 Pixels @ 002,010 */ 18, 0x00, 
  /* ABS: 006 Pixels @ 020,010 */ 0, 6, 0x26, 0xAD, 0xFB, 0xFF, 0xFF, 0x74, 
  /* RLE: 019 Pixels @ 002,011 */ 19, 0x00, 
  /* ABS: 005 Pixels @ 021,011 */ 0, 5, 0x04, 0xA5, 0xFF, 0xFF, 0x74, 
  /* RLE: 019 Pixels @ 002,012 */ 19, 0x00, 
  /* ABS: 005 Pixels @ 021,012 */ 0, 5, 0x04, 0x9D, 0xFF, 0xFF, 0x74, 
  /* RLE: 018 Pixels @ 002,013 */ 18, 0x00, 
  /* ABS: 006 Pixels @ 020,013 */ 0, 6, 0x20, 0xA7, 0xFB, 0xFF, 0xFF, 0x74, 
  /* RLE: 016 Pixels @ 002,014 */ 16, 0x00, 
  /* ABS: 003 Pixels @ 018,014 */ 0, 3, 0x0A, 0x76, 0xE9, 
  /* RLE: 004 Pixels @ 021,014 */ 4, 0xFF, 
  /* RLE: 001 Pixels @ 001,015 */ 1, 0x74, 
  /* RLE: 014 Pixels @ 002,015 */ 14, 0x00, 
  /* ABS: 003 Pixels @ 016,015 */ 0, 3, 0x06, 0x52, 0xDD, 
  /* RLE: 006 Pixels @ 019,015 */ 6, 0xFF, 
  /* RLE: 001 Pixels @ 001,016 */ 1, 0x74, 
  /* RLE: 012 Pixels @ 002,016 */ 12, 0x00, 
  /* ABS: 004 Pixels @ 014,016 */ 0, 4, 0x02, 0x36, 0xB9, 0xFB, 
  /* RLE: 007 Pixels @ 018,016 */ 7, 0xFF, 
  /* RLE: 001 Pixels @ 001,017 */ 1, 0x74, 
  /* RLE: 011 Pixels @ 002,017 */ 11, 0x00, 
  /* ABS: 003 Pixels @ 013,017 */ 0, 3, 0x16, 0x93, 0xF7, 
  /* RLE: 009 Pixels @ 016,017 */ 9, 0xFF, 
  /* RLE: 001 Pixels @ 001,018 */ 1, 0x74, 
  /* RLE: 009 Pixels @ 002,018 */ 9, 0x00, 
  /* ABS: 003 Pixels @ 011,018 */ 0, 3, 0x0C, 0x72, 0xEB, 
  /* RLE: 011 Pixels @ 014,018 */ 11, 0xFF, 
  /* RLE: 001 Pixels @ 001,019 */ 1, 0x74, 
  /* RLE: 007 Pixels @ 002,019 */ 7, 0x00, 
  /* ABS: 003 Pixels @ 009,019 */ 0, 3, 0x06, 0x4C, 0xCF, 
  /* RLE: 013 Pixels @ 012,019 */ 13, 0xFF, 
  /* RLE: 001 Pixels @ 001,020 */ 1, 0x76, 
  /* RLE: 006 Pixels @ 002,020 */ 6, 0x00, 
  /* ABS: 003 Pixels @ 008,020 */ 0, 3, 0x28, 0xB3, 0xFB, 
  /* RLE: 014 Pixels @ 011,020 */ 14, 0xFF, 
  /* RLE: 001 Pixels @ 001,021 */ 1, 0x76, 
  /* RLE: 004 Pixels @ 002,021 */ 4, 0x00, 
  /* ABS: 003 Pixels @ 006,021 */ 0, 3, 0x18, 0x8F, 0xF7, 
  /* RLE: 016 Pixels @ 009,021 */ 16, 0xFF, 
  /* ABS: 006 Pixels @ 001,022 */ 0, 6, 0x7C, 0x00, 0x00, 0x0C, 0x64, 0xE3, 
  /* RLE: 018 Pixels @ 007,022 */ 18, 0xFF, 
  /* ABS: 004 Pixels @ 001,023 */ 0, 4, 0xBD, 0x14, 0x4A, 0xC7, 
  /* RLE: 019 Pixels @ 005,023 */ 19, 0xFF, 
  0
};  // 254 bytes for 576 pixels

GUI_CONST_STORAGE GUI_BITMAP bmplay = {
  24, // xSize
  24, // ySize
  24, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acplay,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
