/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: stop                                                  *
* Dimensions:  24 * 24                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmstop;

static GUI_CONST_STORAGE unsigned char _acstop[] = {
  /* ABS: 010 Pixels @ 000,000 */ 0, 10, 0x8B, 0x1A, 0x12, 0x10, 0x0E, 0x0E, 0x0E, 0x0C, 0x0C, 0x0C, 
  /* RLE: 008 Pixels @ 010,000 */ 8, 0x0E, 
  /* RLE: 004 Pixels @ 018,000 */ 4, 0x10, 
  /* ABS: 003 Pixels @ 022,000 */ 0, 3, 0x14, 0x89, 0x1C, 
  /* RLE: 022 Pixels @ 001,001 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,001 */ 0, 2, 0x1C, 0x12, 
  /* RLE: 022 Pixels @ 001,002 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,002 */ 0, 2, 0x12, 0x10, 
  /* RLE: 022 Pixels @ 001,003 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,003 */ 0, 2, 0x0E, 0x0E, 
  /* RLE: 022 Pixels @ 001,004 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,004 */ 0, 2, 0x0E, 0x0E, 
  /* RLE: 022 Pixels @ 001,005 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,005 */ 0, 2, 0x0C, 0x0E, 
  /* RLE: 022 Pixels @ 001,006 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,006 */ 0, 2, 0x0C, 0x0E, 
  /* RLE: 022 Pixels @ 001,007 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,007 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,008 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,008 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,009 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,009 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,010 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,010 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,011 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,011 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,012 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,012 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,013 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,013 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,014 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,014 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,015 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,015 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,016 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,016 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,017 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,017 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,018 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,018 */ 0, 2, 0x0C, 0x0C, 
  /* RLE: 022 Pixels @ 001,019 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,019 */ 0, 2, 0x0E, 0x0C, 
  /* RLE: 022 Pixels @ 001,020 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,020 */ 0, 2, 0x0E, 0x0C, 
  /* RLE: 022 Pixels @ 001,021 */ 22, 0x00, 
  /* ABS: 002 Pixels @ 023,021 */ 0, 2, 0x12, 0x10, 
  /* RLE: 022 Pixels @ 001,022 */ 22, 0x00, 
  /* ABS: 004 Pixels @ 023,022 */ 0, 4, 0x1A, 0x85, 0x18, 0x0E, 
  /* RLE: 019 Pixels @ 003,023 */ 19, 0x0C, 
  /* ABS: 002 Pixels @ 022,023 */ 0, 2, 0x10, 0x85, 
  0
};  // 161 bytes for 576 pixels

GUI_CONST_STORAGE GUI_BITMAP bmstop = {
  24, // xSize
  24, // ySize
  24, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acstop,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
