/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: usb                                                   *
* Dimensions:  48 * 48                                               *
* NumColors:   None, only alpha channel                              *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmusb;

static GUI_CONST_STORAGE unsigned char _acusb[] = {
  /* RLE: 022 Pixels @ 000,000 */ 22, 0xFF, 
  /* ABS: 004 Pixels @ 022,000 */ 0, 4, 0xFD, 0xAF, 0xA7, 0xFD, 
  /* RLE: 044 Pixels @ 026,000 */ 44, 0xFF, 
  /* ABS: 004 Pixels @ 022,001 */ 0, 4, 0xDF, 0x3E, 0x3A, 0xDD, 
  /* RLE: 043 Pixels @ 026,001 */ 43, 0xFF, 
  /* ABS: 006 Pixels @ 021,002 */ 0, 6, 0xFB, 0x8D, 0x0C, 0x0A, 0x8B, 0xF9, 
  /* RLE: 042 Pixels @ 027,002 */ 42, 0xFF, 
  /* ABS: 006 Pixels @ 021,003 */ 0, 6, 0xC9, 0x26, 0x00, 0x00, 0x24, 0xC7, 
  /* RLE: 042 Pixels @ 027,003 */ 42, 0xFF, 
  /* RLE: 001 Pixels @ 021,004 */ 1, 0x6A, 
  /* RLE: 004 Pixels @ 022,004 */ 4, 0x00, 
  /* RLE: 001 Pixels @ 026,004 */ 1, 0x66, 
  /* RLE: 042 Pixels @ 027,004 */ 42, 0xFF, 
  /* ABS: 006 Pixels @ 021,005 */ 0, 6, 0xCD, 0xAF, 0x28, 0x26, 0xAD, 0xCD, 
  /* RLE: 043 Pixels @ 027,005 */ 43, 0xFF, 
  /* ABS: 004 Pixels @ 022,006 */ 0, 4, 0xE9, 0x34, 0x34, 0xE5, 
  /* RLE: 044 Pixels @ 026,006 */ 44, 0xFF, 
  /* ABS: 004 Pixels @ 022,007 */ 0, 4, 0xEB, 0x34, 0x34, 0xE7, 
  /* RLE: 044 Pixels @ 026,007 */ 44, 0xFF, 
  /* ABS: 004 Pixels @ 022,008 */ 0, 4, 0xEB, 0x34, 0x34, 0xE5, 
  /* RLE: 044 Pixels @ 026,008 */ 44, 0xFF, 
  /* ABS: 008 Pixels @ 022,009 */ 0, 8, 0xE9, 0x34, 0x34, 0xE5, 0xFF, 0xFF, 0xFF, 0x83, 
  /* RLE: 004 Pixels @ 030,009 */ 4, 0x50, 
  /* ABS: 002 Pixels @ 034,009 */ 0, 2, 0x9D, 0xF9, 
  /* RLE: 034 Pixels @ 036,009 */ 34, 0xFF, 
  /* ABS: 008 Pixels @ 022,010 */ 0, 8, 0xEB, 0x34, 0x34, 0xE7, 0xFF, 0xFF, 0xFF, 0x4A, 
  /* RLE: 004 Pixels @ 030,010 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 034,010 */ 0, 2, 0x70, 0xF7, 
  /* RLE: 034 Pixels @ 036,010 */ 34, 0xFF, 
  /* ABS: 008 Pixels @ 022,011 */ 0, 8, 0xEB, 0x34, 0x34, 0xE5, 0xFF, 0xFF, 0xFF, 0x4C, 
  /* RLE: 004 Pixels @ 030,011 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 034,011 */ 0, 2, 0x72, 0xF9, 
  /* RLE: 034 Pixels @ 036,011 */ 34, 0xFF, 
  /* ABS: 008 Pixels @ 022,012 */ 0, 8, 0xE9, 0x34, 0x34, 0xE7, 0xFF, 0xFF, 0xFF, 0x4E, 
  /* RLE: 004 Pixels @ 030,012 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 034,012 */ 0, 2, 0x74, 0xF9, 
  /* RLE: 034 Pixels @ 036,012 */ 34, 0xFF, 
  /* ABS: 008 Pixels @ 022,013 */ 0, 8, 0xEB, 0x34, 0x34, 0xE7, 0xFF, 0xFF, 0xFF, 0x50, 
  /* RLE: 004 Pixels @ 030,013 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 034,013 */ 0, 2, 0x76, 0xFB, 
  /* RLE: 034 Pixels @ 036,013 */ 34, 0xFF, 
  /* ABS: 014 Pixels @ 022,014 */ 0, 14, 0xEB, 0x34, 0x34, 0xE7, 0xFF, 0xFF, 0xFF, 0x97, 0x4E, 0x12, 0x10, 0x5E, 0xAD, 0xFD, 
  /* RLE: 026 Pixels @ 036,014 */ 26, 0xFF, 
  /* ABS: 004 Pixels @ 014,015 */ 0, 4, 0xF9, 0xDB, 0xD9, 0xF1, 
  /* RLE: 004 Pixels @ 018,015 */ 4, 0xFF, 
  /* ABS: 004 Pixels @ 022,015 */ 0, 4, 0xE9, 0x34, 0x34, 0xE7, 
  /* RLE: 004 Pixels @ 026,015 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 030,015 */ 0, 3, 0xD9, 0x34, 0x2C, 
  /* RLE: 028 Pixels @ 033,015 */ 28, 0xFF, 
  /* ABS: 013 Pixels @ 013,016 */ 0, 13, 0xF3, 0x95, 0x38, 0x32, 0x6A, 0xF1, 0xFF, 0xFF, 0xFF, 0xEB, 0x34, 0x34, 0xE7, 
  /* RLE: 004 Pixels @ 026,016 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 030,016 */ 0, 3, 0xD9, 0x34, 0x2C, 
  /* RLE: 028 Pixels @ 033,016 */ 28, 0xFF, 
  /* ABS: 013 Pixels @ 013,017 */ 0, 13, 0xB5, 0x1E, 0x00, 0x00, 0x04, 0x95, 0xFF, 0xFF, 0xFF, 0xEB, 0x34, 0x34, 0xE7, 
  /* RLE: 004 Pixels @ 026,017 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 030,017 */ 0, 3, 0xD9, 0x32, 0x2E, 
  /* RLE: 028 Pixels @ 033,017 */ 28, 0xFF, 
  /* ABS: 013 Pixels @ 013,018 */ 0, 13, 0x85, 0x02, 0x00, 0x00, 0x00, 0x52, 0xFF, 0xFF, 0xFF, 0xE9, 0x34, 0x34, 0xE7, 
  /* RLE: 004 Pixels @ 026,018 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 030,018 */ 0, 3, 0xD5, 0x2E, 0x36, 
  /* RLE: 028 Pixels @ 033,018 */ 28, 0xFF, 
  /* ABS: 013 Pixels @ 013,019 */ 0, 13, 0xA1, 0x10, 0x00, 0x00, 0x00, 0x7A, 0xFF, 0xFF, 0xFF, 0xEB, 0x34, 0x34, 0xE7, 
  /* RLE: 004 Pixels @ 026,019 */ 4, 0xFF, 
  /* ABS: 003 Pixels @ 030,019 */ 0, 3, 0xC9, 0x1A, 0x54, 
  /* RLE: 028 Pixels @ 033,019 */ 28, 0xFF, 
  /* ABS: 020 Pixels @ 013,020 */ 0, 20, 0xE9, 0x62, 0x00, 0x00, 0x32, 0xE3, 0xFF, 0xFF, 0xFF, 0xEB, 0x34, 0x34, 0xE7, 0xFF, 0xFF, 0xFF, 0xFD, 0x66, 0x04, 0x99, 
  /* RLE: 030 Pixels @ 033,020 */ 30, 0xFF, 
  /* ABS: 003 Pixels @ 015,021 */ 0, 3, 0x2C, 0x2C, 0xD5, 
  /* RLE: 004 Pixels @ 018,021 */ 4, 0xFF, 
  /* ABS: 011 Pixels @ 022,021 */ 0, 11, 0xE9, 0x34, 0x34, 0xE7, 0xFF, 0xFF, 0xEB, 0x70, 0x04, 0x54, 0xE5, 
  /* RLE: 030 Pixels @ 033,021 */ 30, 0xFF, 
  /* ABS: 003 Pixels @ 015,022 */ 0, 3, 0x34, 0x2E, 0xD7, 
  /* RLE: 004 Pixels @ 018,022 */ 4, 0xFF, 
  /* ABS: 010 Pixels @ 022,022 */ 0, 10, 0xEB, 0x34, 0x34, 0xE7, 0xFF, 0xE9, 0x6E, 0x0C, 0x46, 0xD1, 
  /* RLE: 031 Pixels @ 032,022 */ 31, 0xFF, 
  /* ABS: 003 Pixels @ 015,023 */ 0, 3, 0x36, 0x2C, 0xD5, 
  /* RLE: 004 Pixels @ 018,023 */ 4, 0xFF, 
  /* ABS: 009 Pixels @ 022,023 */ 0, 9, 0xE9, 0x34, 0x34, 0xE7, 0xFB, 0x62, 0x0C, 0x30, 0xDB, 
  /* RLE: 032 Pixels @ 031,023 */ 32, 0xFF, 
  /* ABS: 003 Pixels @ 015,024 */ 0, 3, 0x3E, 0x2A, 0xD5, 
  /* RLE: 004 Pixels @ 018,024 */ 4, 0xFF, 
  /* ABS: 008 Pixels @ 022,024 */ 0, 8, 0xE9, 0x34, 0x32, 0xC9, 0x5C, 0x06, 0x4E, 0xDF, 
  /* RLE: 033 Pixels @ 030,024 */ 33, 0xFF, 
  /* ABS: 003 Pixels @ 015,025 */ 0, 3, 0x48, 0x24, 0xD1, 
  /* RLE: 004 Pixels @ 018,025 */ 4, 0xFF, 
  /* ABS: 007 Pixels @ 022,025 */ 0, 7, 0xE9, 0x34, 0x1C, 0x48, 0x08, 0x52, 0xD7, 
  /* RLE: 034 Pixels @ 029,025 */ 34, 0xFF, 
  /* ABS: 003 Pixels @ 015,026 */ 0, 3, 0x64, 0x10, 0xBD, 
  /* RLE: 004 Pixels @ 018,026 */ 4, 0xFF, 
  /* ABS: 006 Pixels @ 022,026 */ 0, 6, 0xE9, 0x34, 0x02, 0x04, 0x3C, 0xE1, 
  /* RLE: 035 Pixels @ 028,026 */ 35, 0xFF, 
  /* ABS: 012 Pixels @ 015,027 */ 0, 12, 0xBB, 0x14, 0x22, 0xD5, 0xFD, 0xFF, 0xFF, 0xE7, 0x34, 0x04, 0x4C, 0xE1, 
  /* RLE: 036 Pixels @ 027,027 */ 36, 0xFF, 
  /* ABS: 011 Pixels @ 015,028 */ 0, 11, 0xF1, 0x81, 0x0E, 0x40, 0xCB, 0xFD, 0xFF, 0xE5, 0x32, 0x1E, 0xBB, 
  /* RLE: 038 Pixels @ 026,028 */ 38, 0xFF, 
  /* ABS: 010 Pixels @ 016,029 */ 0, 10, 0xED, 0x74, 0x04, 0x3E, 0xD5, 0xFF, 0xE5, 0x32, 0x2E, 0xDD, 
  /* RLE: 040 Pixels @ 026,029 */ 40, 0xFF, 
  /* ABS: 008 Pixels @ 018,030 */ 0, 8, 0x76, 0x0E, 0x22, 0xD1, 0xE1, 0x32, 0x32, 0xE3, 
  /* RLE: 040 Pixels @ 026,030 */ 40, 0xFF, 
  /* ABS: 008 Pixels @ 018,031 */ 0, 8, 0xEF, 0x7E, 0x10, 0x38, 0xA1, 0x2C, 0x32, 0xE5, 
  /* RLE: 041 Pixels @ 026,031 */ 41, 0xFF, 
  /* ABS: 007 Pixels @ 019,032 */ 0, 7, 0xEF, 0x85, 0x02, 0x1C, 0x0C, 0x32, 0xE5, 
  /* RLE: 043 Pixels @ 026,032 */ 43, 0xFF, 
  /* ABS: 005 Pixels @ 021,033 */ 0, 5, 0x87, 0x12, 0x00, 0x34, 0xE5, 
  /* RLE: 043 Pixels @ 026,033 */ 43, 0xFF, 
  /* ABS: 005 Pixels @ 021,034 */ 0, 5, 0xF1, 0x78, 0x0A, 0x34, 0xE7, 
  /* RLE: 044 Pixels @ 026,034 */ 44, 0xFF, 
  /* ABS: 004 Pixels @ 022,035 */ 0, 4, 0xD1, 0x28, 0x34, 0xE7, 
  /* RLE: 044 Pixels @ 026,035 */ 44, 0xFF, 
  /* ABS: 004 Pixels @ 022,036 */ 0, 4, 0xE9, 0x34, 0x34, 0xE5, 
  /* RLE: 044 Pixels @ 026,036 */ 44, 0xFF, 
  /* ABS: 004 Pixels @ 022,037 */ 0, 4, 0xEB, 0x34, 0x34, 0xE7, 
  /* RLE: 044 Pixels @ 026,037 */ 44, 0xFF, 
  /* ABS: 004 Pixels @ 022,038 */ 0, 4, 0xEB, 0x34, 0x34, 0xE7, 
  /* RLE: 042 Pixels @ 026,038 */ 42, 0xFF, 
  /* ABS: 008 Pixels @ 020,039 */ 0, 8, 0xFD, 0xBF, 0x58, 0x0C, 0x0C, 0x5A, 0xBF, 0xFD, 
  /* RLE: 040 Pixels @ 028,039 */ 40, 0xFF, 
  /* ABS: 002 Pixels @ 020,040 */ 0, 2, 0xBF, 0x1E, 
  /* RLE: 004 Pixels @ 022,040 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 026,040 */ 0, 2, 0x1E, 0xBD, 
  /* RLE: 039 Pixels @ 028,040 */ 39, 0xFF, 
  /* ABS: 002 Pixels @ 019,041 */ 0, 2, 0xE7, 0x46, 
  /* RLE: 006 Pixels @ 021,041 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 027,041 */ 0, 2, 0x42, 0xE3, 
  /* RLE: 038 Pixels @ 029,041 */ 38, 0xFF, 
  /* ABS: 002 Pixels @ 019,042 */ 0, 2, 0xAB, 0x16, 
  /* RLE: 006 Pixels @ 021,042 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 027,042 */ 0, 2, 0x14, 0xA7, 
  /* RLE: 038 Pixels @ 029,042 */ 38, 0xFF, 
  /* ABS: 002 Pixels @ 019,043 */ 0, 2, 0x9B, 0x0C, 
  /* RLE: 006 Pixels @ 021,043 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 027,043 */ 0, 2, 0x0C, 0x99, 
  /* RLE: 038 Pixels @ 029,043 */ 38, 0xFF, 
  /* ABS: 002 Pixels @ 019,044 */ 0, 2, 0xAB, 0x16, 
  /* RLE: 006 Pixels @ 021,044 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 027,044 */ 0, 2, 0x16, 0xAB, 
  /* RLE: 038 Pixels @ 029,044 */ 38, 0xFF, 
  /* ABS: 002 Pixels @ 019,045 */ 0, 2, 0xE7, 0x44, 
  /* RLE: 006 Pixels @ 021,045 */ 6, 0x00, 
  /* ABS: 002 Pixels @ 027,045 */ 0, 2, 0x44, 0xE7, 
  /* RLE: 039 Pixels @ 029,045 */ 39, 0xFF, 
  /* ABS: 002 Pixels @ 020,046 */ 0, 2, 0xBF, 0x20, 
  /* RLE: 004 Pixels @ 022,046 */ 4, 0x00, 
  /* ABS: 002 Pixels @ 026,046 */ 0, 2, 0x1C, 0xBB, 
  /* RLE: 040 Pixels @ 028,046 */ 40, 0xFF, 
  /* ABS: 008 Pixels @ 020,047 */ 0, 8, 0xFD, 0xC3, 0x64, 0x24, 0x24, 0x60, 0xBF, 0xFD, 
  /* RLE: 020 Pixels @ 028,047 */ 20, 0xFF, 
  0
};  // 686 bytes for 2304 pixels

GUI_CONST_STORAGE GUI_BITMAP bmusb = {
  48, // xSize
  48, // ySize
  48, // BytesPerLine
  GUI_COMPRESS_RLE8, // BitsPerPixel
  (unsigned char *)_acusb,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLEALPHA
};

/*************************** End of file ****************************/
