/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "ACCELDLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 	(GUI_ID_USER + 0x00 + 0x40)
#define ID_GRAPH_0 		(GUI_ID_USER + 0x01 + 0x40)
#define ID_TEXT_0 		(GUI_ID_USER + 0x02 + 0x40)
#define ID_BUTTON_0 	(GUI_ID_USER + 0x03 + 0x40)
#define ID_CHECKBOX_0 	(GUI_ID_USER + 0x04 + 0x40)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/


// USER START (Optionally insert additional static data)
#define BK_COLOR_1       0x880000
#define COLOR_BK         GUI_DARKGRAY
#define COLOR_BORDER     BK_COLOR_1
#define COLOR_FRAME      GUI_BLACK
#define COLOR_GRID       GUI_DARKGRAY


#define GRAPH_DIV        9   // (2^9 = 512) If this value is changed _aWaves[] need to be changed too!
#define GRID_DIST_X      50
#define GRID_DIST_Y      20
#define GRID_OFF_Y       0

#define TICK_DIST_H      25
#define TICK_DIST_V      20
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "ACCEL", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ACCELEROMETER", ID_TEXT_0, 122, 7, 269, 35, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Close", ID_BUTTON_0, 420, 8, 50, 30, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 0, 46, 480, 230, 0, 0x0, 0 },
  { CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, 15, 12, 80, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  GRAPH_SCALE_Handle hScaleH, hScaleV;
//  GRAPH_DATA_Handle hData;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Graph'
    //
	WINDOW_SetBkColor(pMsg->hWin, GUI_DARKGRAY);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 30, 10, 10, 30);

   GRAPH_SetColor (hItem, GUI_WHITE,     GRAPH_CI_BK);
   GRAPH_SetColor (hItem, GUI_DARKGRAY, GRAPH_CI_BORDER);
   GRAPH_SetColor (hItem, GUI_ORANGE,  GRAPH_CI_FRAME);
   GRAPH_SetColor (hItem, GUI_GRAY,   GRAPH_CI_GRID);
   WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
    //
    // Adjust grid
    //
    GRAPH_SetGridVis  (hItem, 1);
    GRAPH_SetGridDistX(hItem, GRID_DIST_X);
    GRAPH_SetGridDistY(hItem, GRID_DIST_Y);

    hScaleH = GRAPH_SCALE_Create(30 >> 1, GUI_TA_VCENTER, GRAPH_SCALE_CF_HORIZONTAL, TICK_DIST_H);
    GRAPH_SCALE_SetTextColor(hScaleH, GUI_ORANGE);
    hScaleV = GRAPH_SCALE_Create(30 >> 1, GUI_TA_HCENTER, GRAPH_SCALE_CF_VERTICAL,   TICK_DIST_V);
    GRAPH_SCALE_SetTextColor(hScaleV, GUI_ORANGE);
    GRAPH_SCALE_SetPos(hScaleH, 215);
    GRAPH_SCALE_SetOff(hScaleH, -5);
    //
    // Show some graphs
    //

    GRAPH_AttachScale(hItem, hScaleH);
    GRAPH_AttachScale(hItem, hScaleV);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    TEXT_SetTextColor(hItem, GUI_ORANGE);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
    CHECKBOX_SetText(hItem, "Log");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Close'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateACCEL
*/
WM_HWIN CreateACCEL(void);
WM_HWIN CreateACCEL(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
