/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "BUZZERDLG.h"
#include "main.h"
#include "stm32f7xx_hal.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 	(GUI_ID_USER + 0x00 + 0x80)
#define ID_TEXT_0 		(GUI_ID_USER + 0x01 + 0x80)
#define ID_TEXT_1 		(GUI_ID_USER + 0x02 + 0x80)
#define ID_BUTTON_0 	(GUI_ID_USER + 0x03 + 0x80)
#define ID_BUTTON_1 	(GUI_ID_USER + 0x04 + 0x80)
#define ID_BUTTON_2 	(GUI_ID_USER + 0x05 + 0x80)
#define ID_SLIDER_0 	(GUI_ID_USER + 0x06 + 0x80)
#define ID_SLIDER_1 	(GUI_ID_USER + 0x07 + 0x80)
#define ID_TEXT_2 		(GUI_ID_USER + 0x08 + 0x80)
#define ID_EDIT_0 		(GUI_ID_USER + 0x09 + 0x80)
#define ID_EDIT_1 		(GUI_ID_USER + 0x0A + 0x80)
#define ID_BUTTON_C 	(GUI_ID_USER + 0x0B + 0x80)
#define ID_BUTTON_D 	(GUI_ID_USER + 0x0C + 0x80)
#define ID_BUTTON_E 	(GUI_ID_USER + 0x0D + 0x80)
#define ID_BUTTON_F 	(GUI_ID_USER + 0x0E + 0x80)
#define ID_BUTTON_G 	(GUI_ID_USER + 0x0F + 0x80)
#define ID_BUTTON_A 	(GUI_ID_USER + 0x10 + 0x80)
#define ID_BUTTON_H 	(GUI_ID_USER + 0x11 + 0x80)


#define ID_BUTTON_C_ 	(GUI_ID_USER + 0x13 + 0x80)
#define ID_BUTTON_D_ 	(GUI_ID_USER + 0x14 + 0x80)
#define ID_BUTTON_F_ 	(GUI_ID_USER + 0x15 + 0x80)
#define ID_BUTTON_G_ 	(GUI_ID_USER + 0x16 + 0x80)
#define ID_BUTTON_A_ 	(GUI_ID_USER + 0x17 + 0x80)


#define TONE_C 		1911
#define TONE_C_ 	1804
#define TONE_D 		1703
#define TONE_D_ 	1607
#define TONE_E 		1517
#define TONE_F	 	1432
#define TONE_F_ 	1351
#define TONE_G	 	1275
#define TONE_G_ 	1204
#define TONE_A 		1136
#define TONE_A_ 	1073
#define TONE_H	 	1013
#define TONE_Ch	 	955


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/

extern TIM_HandleTypeDef htim4;

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "BUZZER", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Buzzer", ID_TEXT_0, 177, 8, 102, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Frequency (Hz)", ID_TEXT_1, 32, 41, 110, 33, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Close", ID_BUTTON_0, 420, 8, 50, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Start", ID_BUTTON_1, 420, 65, 50, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Stop", ID_BUTTON_2, 420, 113, 50, 30, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 30, 68, 320, 20, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 30, 118, 320, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Volume (%)", ID_TEXT_2, 29, 97, 80, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 360, 70, 42, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 360, 118, 42, 20, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "C", ID_BUTTON_C, 0, 172, 68, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "D", ID_BUTTON_D, 68, 172, 69, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "E", ID_BUTTON_E, 137, 172, 68, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "F", ID_BUTTON_F, 205, 172, 69, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "G", ID_BUTTON_G, 274, 172, 68, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "A", ID_BUTTON_A, 342, 172, 69, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "H", ID_BUTTON_H, 411, 172, 69, 100, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "C#", ID_BUTTON_C_, 48, 172, 40, 55, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "D#", ID_BUTTON_D_, 117, 172, 40, 55, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "F#", ID_BUTTON_F_, 254, 172, 40, 55, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "G#", ID_BUTTON_G_, 322, 172, 40, 55, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "b", ID_BUTTON_A_, 391, 172, 40, 55, 0, 0x0, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};

int buzzer_period=100;
int buzzer_volume=100;
char data[20]={0};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  int i;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'BUZZER'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_MAKE_COLOR(0x000080FF));
    //
    // Initialization of 'Buzzer'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    //
    // Initialization of 'Frequency (Hz)'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    //
    // Initialization of 'Volume (%)'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_16B_1);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "1000");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "50");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_13B_1);
    // USER START (Optionally insert additional code for further widget initialization)

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    SLIDER_SetRange(hItem, 67, 1000);
    SLIDER_SetValue(hItem, 1000);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
    SLIDER_SetRange(hItem, 0, 100);
    SLIDER_SetValue(hItem, 50);


    for(i=0; i<7; i++)
    {
  	    hItem = WM_GetDialogItem(pMsg->hWin, _aDialogCreate[i + 11].Id);
  	    BUTTON_SetSkinClassic(hItem);
  	    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
  	    BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_LIGHTGRAY);
  	    BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_BLACK);
  	    BUTTON_SetFrameColor(hItem, GUI_ORANGE);
  	    BUTTON_SetFocussable(hItem, 0);

    }
    for(i=0; i<5; i++)
    {
  	    hItem = WM_GetDialogItem(pMsg->hWin, _aDialogCreate[i + 18].Id);
  	    BUTTON_SetSkinClassic(hItem);
  	    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_BLACK);
  	    BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_DARKGRAY);
  	    BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_WHITE);
  	    BUTTON_SetFrameColor(hItem, GUI_ORANGE);
  	    BUTTON_SetFocussable(hItem, 0);
    }


    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
	case ID_BUTTON_0: // Notifications sent by 'Close'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_BUTTON_1: // Notifications sent by 'Start'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:

		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		  HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_BUTTON_2: // Notifications sent by 'Stop'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_SLIDER_0: // Notifications sent by 'Slider'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_VALUE_CHANGED:
		  buzzer_period=SLIDER_GetValue(WM_GetDialogItem(pMsg->hWin, Id));
		  sprintf((char*)data, "%d", 1000000/buzzer_period);
		  EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),data);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);

		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_SLIDER_1: // Notifications sent by 'Slider'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_VALUE_CHANGED:
		  buzzer_volume=SLIDER_GetValue(WM_GetDialogItem(pMsg->hWin, Id));
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  sprintf((char*)data, "%d", buzzer_volume);
		  EDIT_SetText(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1),data);
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_BUTTON_C: // Notifications sent by 'C'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_C);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_C>>1);

		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
			HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
			  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
			  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_BUTTON_D: // Notifications sent by 'D'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_D);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_D>>1);
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		// USER END
		break;
	  case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_BUTTON_E: // Notifications sent by 'E'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_E);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_E>>1);
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		// USER END
		  break;
	  case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_BUTTON_F: // Notifications sent by 'F'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_F);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_F>>1);
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		// USER END
		break;
	  case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_BUTTON_G: // Notifications sent by 'G'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_G);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_G>>1);

		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		// USER END
		break;
	  case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_BUTTON_A: // Notifications sent by 'A'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_A);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_A>>1);

		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		// USER END
		break;
	  case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_BUTTON_H: // Notifications sent by 'H'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_H);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_H>>1);
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		// USER END
		break;
	  case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;

	case ID_BUTTON_C_: // Notifications sent by 'C#'
	   switch(NCode) {
	   case WM_NOTIFICATION_CLICKED:
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_C_);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_C_>>1);

		 // USER START (Optionally insert code for reacting on notification message)
		 // USER END
		 break;
	   case WM_NOTIFICATION_RELEASED:
			HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
			  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
			  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		 // USER START (Optionally insert code for reacting on notification message)
		 // USER END
		 break;
	   case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	   // USER START (Optionally insert additional code for further notification handling)
	   // USER END
	   }
	   break;
	case ID_BUTTON_D_: // Notifications sent by 'D#'
	   switch(NCode) {
	   case WM_NOTIFICATION_CLICKED:
		 // USER START (Optionally insert code for reacting on notification message)
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_D_);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_D_>>1);
		 // USER END
		 break;
	   case WM_NOTIFICATION_RELEASED:
		 // USER START (Optionally insert code for reacting on notification message)
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		 // USER END
		 break;
	   case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	   // USER START (Optionally insert additional code for further notification handling)
	   // USER END
	   }
	   break;
	case ID_BUTTON_F_: // Notifications sent by 'F#'
	   switch(NCode) {
	   case WM_NOTIFICATION_CLICKED:
		 // USER START (Optionally insert code for reacting on notification message)
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_F_);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_F_>>1);
		 // USER END
		 break;
	   case WM_NOTIFICATION_RELEASED:
		 // USER START (Optionally insert code for reacting on notification message)
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		 // USER END
		 break;
	   case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	   // USER START (Optionally insert additional code for further notification handling)
	   // USER END
	   }
	   break;
	case ID_BUTTON_G_: // Notifications sent by 'G#'
	   switch(NCode) {
	   case WM_NOTIFICATION_CLICKED:
		 // USER START (Optionally insert code for reacting on notification message)
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_G_);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_G_>>1);

		 // USER END
		 break;
	   case WM_NOTIFICATION_RELEASED:
		 // USER START (Optionally insert code for reacting on notification message)
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		 // USER END
		 break;
	   case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	   // USER START (Optionally insert additional code for further notification handling)
	   // USER END
	   }
	   break;
	case ID_BUTTON_A_: // Notifications sent by 'A#'
	   switch(NCode) {
	   case WM_NOTIFICATION_CLICKED:
		 // USER START (Optionally insert code for reacting on notification message)
			HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
			__HAL_TIM_SetAutoreload(&htim4, TONE_A_);
			__HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, TONE_A_>>1);

		 // USER END
		 break;
	   case WM_NOTIFICATION_RELEASED:
		 // USER START (Optionally insert code for reacting on notification message)
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		 // USER END
		 break;
	   case WM_NOTIFICATION_MOVED_OUT:
		  HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_3);
		  __HAL_TIM_SetCompare(&htim4, TIM_CHANNEL_3, (buzzer_volume*buzzer_period)/1000);
		  __HAL_TIM_SetAutoreload(&htim4, buzzer_period);
		  break;
	   // USER START (Optionally insert additional code for further notification handling)
	   // USER END
	   }
	   break;
	case ID_EDIT_0: // Notifications sent by 'Edit'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_VALUE_CHANGED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
	  }
	  break;
	case ID_EDIT_1: // Notifications sent by 'Edit'
	  switch(NCode) {
	  case WM_NOTIFICATION_CLICKED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_RELEASED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  case WM_NOTIFICATION_VALUE_CHANGED:
		// USER START (Optionally insert code for reacting on notification message)
		// USER END
		break;
	  // USER START (Optionally insert additional code for further notification handling)
	  // USER END
		  }
		  break;
		// USER START (Optionally insert additional code for further Ids)
		// USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateBUZZER
*/
WM_HWIN CreateBUZZER(void);
WM_HWIN CreateBUZZER(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
