/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "FILESDLG.h"
#include "fatfs.h"
#include "string.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 	(GUI_ID_USER + 0x00 + 0xB0)
#define ID_TREEVIEW_0	(GUI_ID_USER + 0x02 + 0xB0)
#define ID_BUTTON_0 	(GUI_ID_USER + 0x03 + 0xB0)
#define ID_TEXT_0 		(GUI_ID_USER + 0x04 + 0xB0)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "FILES", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TREEVIEW_CreateIndirect, "Treeview", ID_TREEVIEW_0, 9, 43, 463, 215, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Close", ID_BUTTON_0, 420, 8, 50, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SD Card", ID_TEXT_0, 170, 6, 110, 31, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/

unsigned char local_disk=0;

FRESULT scan_files (char* path, WM_HWIN hTree, TREEVIEW_ITEM_Handle hNode)
{
    FRESULT res;
    DIR dir;
    UINT i=0;

    static FILINFO fno;
    TREEVIEW_ITEM_Handle hItem;
    char buff[270];
    hItem=hNode;


    strcpy(fno.fname,buff);
    fno.fsize = 255;

    res = f_opendir(&dir, path);                       /* Open the directory */

    if (res == FR_OK)
    {

        for (;;)
        {
            res = f_readdir(&dir, &fno);                   /* Read a directory item */
            if (res != FR_OK || fno.fname[0] == 0) break;  /* Break on error or end of dir */

            if (fno.fattrib & AM_DIR)
            {/* It is a directory */
            	if(i==0) hItem = TREEVIEW_InsertItem(hTree, TREEVIEW_ITEM_TYPE_NODE, hItem, TREEVIEW_INSERT_FIRST_CHILD, fno.fname[0] ? fno.fname : fno.fname);
            	else hItem = TREEVIEW_InsertItem(hTree, TREEVIEW_ITEM_TYPE_NODE, hItem, TREEVIEW_INSERT_BELOW, fno.fname[0] ? fno.fname : fno.fname);
            	sprintf(buff, "%s/%s", path, fno.fname);
            	scan_files(buff, hTree, hItem);                    /* Enter the directory */


            }
            else
            {/* It is a file. */
            	if(i==0) hItem = TREEVIEW_InsertItem(hTree, TREEVIEW_ITEM_TYPE_LEAF, hItem, TREEVIEW_INSERT_FIRST_CHILD,  fno.fname[0] ? fno.fname : fno.fname);
            	else hItem = TREEVIEW_InsertItem(hTree, TREEVIEW_ITEM_TYPE_LEAF, hItem, TREEVIEW_INSERT_BELOW,  fno.fname[0] ? fno.fname : fno.fname);
            }
            i++;

        }
        f_closedir(&dir);

    }
    TREEVIEW_SetAutoScrollH(hTree, 1);
    TREEVIEW_SetAutoScrollV(hTree, 1);
    TREEVIEW_ITEM_Expand(TREEVIEW_GetItem(hTree, 0, TREEVIEW_GET_FIRST));
    WM_SetFocus(hTree);

    return res;
}

static void _cbDialog(WM_MESSAGE * pMsg) {

  TREEVIEW_ITEM_Handle hNode;
  WM_HWIN                hItem;
  int                    NCode;
  int                    Id;
  FATFS myFAT;

  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Treeview'
	hItem = pMsg->hWin;
	WINDOW_SetBkColor(hItem, GUI_WHITE);
    //
	hItem = WM_GetDialogItem(pMsg->hWin, ID_TREEVIEW_0);

	FATFS_LinkDriver(&SD_Driver, SDPath);
	f_mount(&myFAT, SDPath, 1);
	hNode = TREEVIEW_InsertItem(hItem, TREEVIEW_ITEM_TYPE_NODE, 0, 0, "Local disk");
	scan_files("", hItem, hNode);
	f_mount(0, SDPath, 1);
	FATFS_UnLinkDriver(SDPath);
	TREEVIEW_SetBkColor(hItem, TREEVIEW_CI_UNSEL, GUI_WHITE);
	TREEVIEW_SetBkColor(hItem, TREEVIEW_CI_SEL, GUI_ORANGE);
	TREEVIEW_SetLineColor(hItem, TREEVIEW_CI_UNSEL, GUI_WHITE);
	TREEVIEW_SetTextColor(hItem, TREEVIEW_CI_UNSEL, GUI_BLACK);
	TREEVIEW_SetTextColor(hItem, TREEVIEW_CI_SEL, GUI_BLACK);

    //
    // Initialization of 'Files'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_32B_1);
    TEXT_SetTextColor(hItem, GUI_BLACK);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_TREEVIEW_0: // Notifications sent by 'Treeview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Close'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFILES
*/
WM_HWIN CreateFILES(void);
WM_HWIN CreateFILES(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
