/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "INFODLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x01 + 0xC0)
#define ID_TEXT_0 	(GUI_ID_USER + 0x02 + 0xC0)
#define ID_BUTTON_0 (GUI_ID_USER + 0x03 + 0xC0)
#define ID_IMAGE_0 	(GUI_ID_USER + 0x04 + 0xC0)
#define ID_IMAGE_1 	(GUI_ID_USER + 0x05 + 0xC0)

extern GUI_CONST_STORAGE GUI_BITMAP bmstm32;
extern GUI_CONST_STORAGE GUI_BITMAP bmmikroe;

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "INFO", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Close", ID_BUTTON_0, 420, 5, 50, 30, 0, 0x0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 372, 63, 104, 99, 0, 0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_1, 388, 176, 73, 73, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/


// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN      hItem;
  int          NCode;
  int          Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'INFO'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_BLACK);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x0046A3FF));

	    TEXT_SetText(hItem, "   Board:\n"
	    				"      Mikromedia+ for STM32F7 ARM\n"
    					"   Processor:\n"
    					"      STM32F746ZG, 216 MHz, 320 KB RAM, 1MB FLASH\n"
    					"   Display: 480x272 px, 16 bpp\n"
    					"      SSD1963 display controller\n"
    					"      STMPE610 touch screen controller\n"
    					"   Middlewares:\n"
    					"      STemWin GUI library, FatFs, ST USB CDC\n"
    					"   Sensors:\n"
    					"      PIN photodiode\n"
    					"      MCP9700A temperature sensor\n"
    					"      ADXL345 accelerometer\n"
    					"   Modules:\n"
    					"      MP3, Buzzer, Ethernet, RF transciever, Flash\n"
    					"   Code built using:\n"
    					"      STM32CubeMX & System Workbench for STM32\n\n\n"
    					"   Author: J. Bajic, bajic@uns.ac.rs");
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    IMAGE_SetBitmap(hItem, &bmstm32);
    //
    // Initialization of 'Image'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_1);
    IMAGE_SetBitmap(hItem, &bmmikroe);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'close'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateINFO
*/
//WM_HWIN CreateINFO(void);
WM_HWIN CreateINFO(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
