/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "MP3DLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_WINDOW_0 	(GUI_ID_USER + 0x00 + 0x90)
#define ID_BUTTON_0 	(GUI_ID_USER + 0x01 + 0x90)
#define ID_BUTTON_1 	(GUI_ID_USER + 0x02 + 0x90)
#define ID_BUTTON_2 	(GUI_ID_USER + 0x03 + 0x90)
#define ID_BUTTON_3 	(GUI_ID_USER + 0x04 + 0x90)
#define ID_BUTTON_4 	(GUI_ID_USER + 0x05 + 0x90)
#define ID_PROGBAR_0 	(GUI_ID_USER + 0x06 + 0x90)
#define ID_SLIDER_0 	(GUI_ID_USER + 0x07 + 0x90)
#define ID_LISTBOX_0 	(GUI_ID_USER + 0x08 + 0x90)
#define ID_BUTTON_5 	(GUI_ID_USER + 0x09 + 0x90)
#define ID_SCROLLBAR_0 	(GUI_ID_USER + 0x0A + 0x90)
#define ID_TEXT_0 		(GUI_ID_USER + 0x0B + 0x90)
#define ID_IMAGE_0  	(GUI_ID_USER + 0x0C + 0x90)
#define ID_TEXT_1 		(GUI_ID_USER + 0x0D + 0x90)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

extern GUI_CONST_STORAGE GUI_BITMAP bmbackward;
extern GUI_CONST_STORAGE GUI_BITMAP bmforward;
extern GUI_CONST_STORAGE GUI_BITMAP bmpause;
extern GUI_CONST_STORAGE GUI_BITMAP bmplay;
extern GUI_CONST_STORAGE GUI_BITMAP bmstop;
extern GUI_CONST_STORAGE GUI_BITMAP bmmusic;
extern GUI_CONST_STORAGE GUI_BITMAP bmclose;
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "MP3", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 332, 50, 128, 128, 0, 0, 0 },
  { BUTTON_CreateIndirect, "Prev", ID_BUTTON_0, 20, 220, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Play", ID_BUTTON_1, 75, 220, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Pause", ID_BUTTON_2, 130, 220, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Stop", ID_BUTTON_3, 185, 220, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Next", ID_BUTTON_4, 240, 220, 50, 40, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 20, 199, 440, 16, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 295, 220, 165, 40, 16, 0x0, 0 },
  { LISTBOX_CreateIndirect, "Listbox", ID_LISTBOX_0, 20, 50, 280, 119, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "", ID_TEXT_0, 20, 180, 440, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "MP3 Player", ID_TEXT_1, 20, 5, 440, 30, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Close", ID_BUTTON_5, 430, 5, 30, 30, 0, 0x0, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};


/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  int i;


  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'MP3'
    //

    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_BLACK);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    IMAGE_SetBitmap(hItem, &bmmusic);


    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextColor(hItem, GUI_WHITE);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextColor(hItem, GUI_ORANGE);
    TEXT_SetBkColor(hItem, GUI_DARKGRAY);
    TEXT_SetFont(hItem, GUI_FONT_20B_1);
    TEXT_SetTextAlign(hItem, TEXT_CF_VCENTER);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);

	WIDGET_SetEffect(hItem, &WIDGET_Effect_None);

    LISTBOX_SetBkColor(hItem, LISTBOX_CI_SEL, GUI_ORANGE);
	LISTBOX_SetBkColor(hItem, LISTBOX_CI_UNSEL, GUI_DARKGRAY);
    LISTBOX_SetBkColor(hItem, LISTBOX_CI_SELFOCUS, GUI_ORANGE);
	LISTBOX_SetBkColor(hItem, LISTBOX_CI_DISABLED, GUI_DARKGRAY);

	LISTBOX_SetTextColor (hItem, LISTBOX_CI_UNSEL, GUI_WHITE);
	LISTBOX_SetTextColor (hItem, LISTBOX_CI_SEL, GUI_BLACK);
	LISTBOX_SetTextColor (hItem, LISTBOX_CI_SELFOCUS, GUI_BLACK);

	LISTBOX_SetScrollbarColor(hItem, SCROLLBAR_CI_ARROW, GUI_ORANGE);
	LISTBOX_SetScrollbarColor(hItem, SCROLLBAR_CI_SHAFT, GUI_LIGHTGRAY);
	LISTBOX_SetScrollbarColor(hItem, SCROLLBAR_CI_THUMB, GUI_DARKGRAY);

	LISTBOX_SetAutoScrollV (hItem, 1);
	hItem=WM_GetScrollbarV(hItem);
	WM_SetId(hItem, ID_SCROLLBAR_0);

	SCROLLBAR_SetSkinClassic(hItem);
	WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
	SCROLLBAR_SetColor(hItem, SCROLLBAR_CI_ARROW, GUI_ORANGE);
	SCROLLBAR_SetColor(hItem, SCROLLBAR_CI_SHAFT, GUI_LIGHTGRAY);
	SCROLLBAR_SetColor(hItem, SCROLLBAR_CI_THUMB, GUI_DARKGRAY);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
	PROGBAR_SetSkinClassic(hItem);
	WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
    PROGBAR_SetBarColor(hItem, 0, GUI_ORANGE);
	PROGBAR_SetBarColor(hItem, 1, GUI_DARKGRAY);

	hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
	SLIDER_SetSkinClassic(hItem);
	WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
	SLIDER_SetBarColor(hItem, GUI_ORANGE);
	SLIDER_SetBkColor(hItem, GUI_DARKGRAY);
	SLIDER_SetNumTicks(hItem, 20);
	SLIDER_SetRange(hItem, 0, 100);
	SLIDER_SetTickColor(hItem, GUI_ORANGE);
	SLIDER_SetValue(hItem, 50);

    for(i=0; i<5; i++)
    {
  	    hItem = WM_GetDialogItem(pMsg->hWin, _aDialogCreate[i + 2].Id);
  	    BUTTON_SetSkinClassic(hItem);
  	    WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
  	    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
  	    BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_BROWN);
  	    BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_ORANGE);
  	    BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_LIGHTGRAY);
  	    BUTTON_SetFrameColor(hItem, GUI_ORANGE);
  	    BUTTON_SetFont(hItem, GUI_FONT_20B_1);
  	    BUTTON_SetFocussable(hItem, 0);
  	    switch(i)
  	    {
  			case 0:
  			    BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED,&bmbackward, 13, 8);
  				break;
  			case 1:
  			    BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED,&bmplay, 13, 8);
  				break;
  			case 2:
  			    BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED,&bmpause, 13, 8);
  				break;
  			case 3:
  			    BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED,&bmstop, 13, 8);
  				break;
  			case 4:
  			    BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED,&bmforward, 13, 8);
  				break;

  	    }

  	    BUTTON_SetText(hItem, "");
    }

	hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
	BUTTON_SetSkinClassic(hItem);
	WIDGET_SetEffect(hItem, &WIDGET_Effect_None);
	BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_DARKGRAY);
	BUTTON_SetBkColor(hItem, BUTTON_CI_PRESSED, GUI_BROWN);
	BUTTON_SetTextColor(hItem, BUTTON_CI_UNPRESSED, GUI_ORANGE);
	BUTTON_SetTextColor(hItem, BUTTON_CI_PRESSED, GUI_LIGHTGRAY);
	BUTTON_SetFrameColor(hItem, GUI_ORANGE);
	BUTTON_SetFont(hItem, GUI_FONT_20B_1);
	BUTTON_SetFocussable(hItem, 0);
	BUTTON_SetBitmapEx(hItem, BUTTON_CI_UNPRESSED,&bmclose, 3, 3);
	BUTTON_SetText(hItem, "");

    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Prev'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Play'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Pause'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Stop'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Next'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
      case ID_LISTBOX_0: // Notifications sent by 'Listbox'
        switch(NCode) {
        case WM_NOTIFICATION_CLICKED:
          // USER START (Optionally insert code for reacting on notification message)
          // USER END
          break;
        case WM_NOTIFICATION_RELEASED:
          // USER START (Optionally insert code for reacting on notification message)
          // USER END
          break;
        case WM_NOTIFICATION_SEL_CHANGED:
          // USER START (Optionally insert code for reacting on notification message)
          // USER END
          break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
        }
        break;
    case ID_BUTTON_5: // Notifications sent by 'Close'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMP3
*/
WM_HWIN CreateMP3(void);
WM_HWIN CreateMP3(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
