/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "QWERTYDLG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00 + 0xF0)
#define ID_BUTTON_1 (GUI_ID_USER + 0x01 + 0xF0)
#define ID_BUTTON_2 (GUI_ID_USER + 0x02 + 0xF0)
#define ID_BUTTON_3 (GUI_ID_USER + 0x03 + 0xF0)
#define ID_BUTTON_4 (GUI_ID_USER + 0x04 + 0xF0)
#define ID_BUTTON_5 (GUI_ID_USER + 0x05 + 0xF0)
#define ID_BUTTON_6 (GUI_ID_USER + 0x06 + 0xF0)
#define ID_BUTTON_7 (GUI_ID_USER + 0x07 + 0xF0)
#define ID_BUTTON_8 (GUI_ID_USER + 0x08 + 0xF0)
#define ID_BUTTON_9 (GUI_ID_USER + 0x09 + 0xF0)
#define ID_BUTTON_0 (GUI_ID_USER + 0x0A + 0xF0)

#define ID_BUTTON_Q (GUI_ID_USER + 0x0B + 0xF0)
#define ID_BUTTON_W (GUI_ID_USER + 0x0C + 0xF0)
#define ID_BUTTON_E (GUI_ID_USER + 0x0D + 0xF0)
#define ID_BUTTON_R (GUI_ID_USER + 0x0E + 0xF0)
#define ID_BUTTON_T (GUI_ID_USER + 0x0F + 0xF0)
#define ID_BUTTON_Y (GUI_ID_USER + 0x10 + 0xF0)
#define ID_BUTTON_U (GUI_ID_USER + 0x11 + 0xF0)
#define ID_BUTTON_I (GUI_ID_USER + 0x12 + 0xF0)
#define ID_BUTTON_O (GUI_ID_USER + 0x13 + 0xF0)
#define ID_BUTTON_P (GUI_ID_USER + 0x14 + 0xF0)

#define ID_BUTTON_A (GUI_ID_USER + 0x15 + 0xF0)
#define ID_BUTTON_S (GUI_ID_USER + 0x16 + 0xF0)
#define ID_BUTTON_D (GUI_ID_USER + 0x17 + 0xF0)
#define ID_BUTTON_F (GUI_ID_USER + 0x18 + 0xF0)
#define ID_BUTTON_G (GUI_ID_USER + 0x19 + 0xF0)
#define ID_BUTTON_H (GUI_ID_USER + 0x1A + 0xF0)
#define ID_BUTTON_J (GUI_ID_USER + 0x1B + 0xF0)
#define ID_BUTTON_K (GUI_ID_USER + 0x1C + 0xF0)
#define ID_BUTTON_L (GUI_ID_USER + 0x1D + 0xF0)

#define ID_BUTTON_Z (GUI_ID_USER + 0x1E + 0xF0)
#define ID_BUTTON_X (GUI_ID_USER + 0x1F + 0xF0)
#define ID_BUTTON_C (GUI_ID_USER + 0x20 + 0xF0)
#define ID_BUTTON_V (GUI_ID_USER + 0x21 + 0xF0)
#define ID_BUTTON_B (GUI_ID_USER + 0x22 + 0xF0)
#define ID_BUTTON_N (GUI_ID_USER + 0x23 + 0xF0)
#define ID_BUTTON_M (GUI_ID_USER + 0x24 + 0xF0)

#define ID_BUTTON_SHIFT (GUI_ID_USER + 0x25 + 0xF0)
#define ID_BUTTON_DEL 	(GUI_ID_USER + 0x26 + 0xF0)
#define ID_BUTTON_SYM 	(GUI_ID_USER + 0x27 + 0xF0)
#define ID_BUTTON_SPACE (GUI_ID_USER + 0x28 + 0xF0)
#define ID_BUTTON_DOT 	(GUI_ID_USER + 0x29 + 0xF0)
#define ID_BUTTON_ENTER (GUI_ID_USER + 0x2A + 0xF0)
#define ID_BUTTON_COMMA (GUI_ID_USER + 0x2B + 0xF0)



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "QWERTY", ID_WINDOW_0, 40, 145, 400, 125, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "1", ID_BUTTON_1, 0, 0, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "2", ID_BUTTON_2, 40, 0, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "3", ID_BUTTON_3, 80, 0, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "4", ID_BUTTON_4, 120, 0, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "5", ID_BUTTON_5, 160, 0, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "6", ID_BUTTON_6, 200, 0, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "7", ID_BUTTON_7, 240, 0, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "8", ID_BUTTON_8, 280, 0, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "9", ID_BUTTON_9, 320, 0, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "0", ID_BUTTON_0, 360, 0, 40, 25, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "Q", ID_BUTTON_Q, 0, 25, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "W", ID_BUTTON_W, 40, 25, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "E", ID_BUTTON_E, 80, 25, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "R", ID_BUTTON_R, 120, 25, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "T", ID_BUTTON_T, 160, 25, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Y", ID_BUTTON_Y, 200, 25, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "U", ID_BUTTON_U, 240, 25, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "I", ID_BUTTON_I, 280, 25, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "O", ID_BUTTON_O, 320, 25, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "P", ID_BUTTON_P, 360, 25, 40, 25, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "A", ID_BUTTON_A, 20, 50, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "S", ID_BUTTON_S, 60, 50, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "D", ID_BUTTON_D, 100, 50, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "F", ID_BUTTON_F, 140, 50, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "G", ID_BUTTON_G, 180, 50, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "H", ID_BUTTON_H, 220, 50, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "J", ID_BUTTON_J, 260, 50, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "K", ID_BUTTON_K, 300, 50, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "L", ID_BUTTON_L, 340, 50, 40, 25, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "Z", ID_BUTTON_Z, 60, 75, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "X", ID_BUTTON_X, 100, 75, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "C", ID_BUTTON_C, 140, 75, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "V", ID_BUTTON_V, 180, 75, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "B", ID_BUTTON_B, 220, 75, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "N", ID_BUTTON_N, 260, 75, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "M", ID_BUTTON_M, 300, 75, 40, 25, 0, 0x0, 0 },

  { BUTTON_CreateIndirect, "Shift", ID_BUTTON_SHIFT, 0, 75, 60, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Del", ID_BUTTON_DEL, 340, 75, 60, 25, 0, 0x0, 0 },


  { BUTTON_CreateIndirect, "Sym", ID_BUTTON_SYM, 0, 100, 60, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ",", ID_BUTTON_COMMA, 60, 100, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Space", ID_BUTTON_SPACE, 100, 100, 200, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ".", ID_BUTTON_DOT, 300, 100, 40, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Enter", ID_BUTTON_ENTER, 340, 100, 60, 25, 0, 0x0, 0 },




  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/


unsigned int qwerty_state=0;

char message[256]={0};
unsigned int cursor=0;

static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  WM_HWIN hItem;

  int i;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:

	    hItem = pMsg->hWin;

	    qwerty_state=0;
	    for(i=0; i<43; i++)
	    {
	  	    hItem = WM_GetDialogItem(pMsg->hWin, _aDialogCreate[i + 1].Id);
	  	    BUTTON_SetFocussable(hItem, 0);
	    }
	  break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_SHIFT: // Notifications sent by 'SHIFT'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
    	  if(qwerty_state==0)
    	  {
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Q);
    		  BUTTON_SetText(hItem, "q");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_W);
    		  BUTTON_SetText(hItem, "w");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_E);
    		  BUTTON_SetText(hItem, "e");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_R);
    		  BUTTON_SetText(hItem, "r");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_T);
    		  BUTTON_SetText(hItem, "t");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Y);
    		  BUTTON_SetText(hItem, "y");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_U);
    		  BUTTON_SetText(hItem, "u");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_I);
    		  BUTTON_SetText(hItem, "i");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_O);
    		  BUTTON_SetText(hItem, "o");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_P);
    		  BUTTON_SetText(hItem, "p");

    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_A);
    		  BUTTON_SetText(hItem, "a");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_S);
    		  BUTTON_SetText(hItem, "s");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_D);
    		  BUTTON_SetText(hItem, "d");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_F);
    		  BUTTON_SetText(hItem, "f");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_G);
    		  BUTTON_SetText(hItem, "g");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_H);
    		  BUTTON_SetText(hItem, "h");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_J);
    		  BUTTON_SetText(hItem, "j");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_K);
    		  BUTTON_SetText(hItem, "k");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_L);
    		  BUTTON_SetText(hItem, "l");

    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Z);
    		  BUTTON_SetText(hItem, "z");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_X);
    		  BUTTON_SetText(hItem, "x");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_C);
    		  BUTTON_SetText(hItem, "c");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_V);
    		  BUTTON_SetText(hItem, "v");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_B);
    		  BUTTON_SetText(hItem, "b");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_N);
    		  BUTTON_SetText(hItem, "n");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_M);
    		  BUTTON_SetText(hItem, "m");

    		  qwerty_state=1;

    	  }
    	  else if(qwerty_state==1)
    	  {
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Q);
    		  BUTTON_SetText(hItem, "Q");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_W);
    		  BUTTON_SetText(hItem, "W");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_E);
    		  BUTTON_SetText(hItem, "E");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_R);
    		  BUTTON_SetText(hItem, "R");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_T);
    		  BUTTON_SetText(hItem, "T");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Y);
    		  BUTTON_SetText(hItem, "Y");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_U);
    		  BUTTON_SetText(hItem, "U");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_I);
    		  BUTTON_SetText(hItem, "I");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_O);
    		  BUTTON_SetText(hItem, "O");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_P);
    		  BUTTON_SetText(hItem, "P");

    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_A);
    		  BUTTON_SetText(hItem, "A");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_S);
    		  BUTTON_SetText(hItem, "S");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_D);
    		  BUTTON_SetText(hItem, "D");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_F);
    		  BUTTON_SetText(hItem, "F");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_G);
    		  BUTTON_SetText(hItem, "G");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_H);
    		  BUTTON_SetText(hItem, "H");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_J);
    		  BUTTON_SetText(hItem, "J");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_K);
    		  BUTTON_SetText(hItem, "K");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_L);
    		  BUTTON_SetText(hItem, "L");

    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Z);
    		  BUTTON_SetText(hItem, "Z");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_X);
    		  BUTTON_SetText(hItem, "X");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_C);
    		  BUTTON_SetText(hItem, "C");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_V);
    		  BUTTON_SetText(hItem, "V");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_B);
    		  BUTTON_SetText(hItem, "B");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_N);
    		  BUTTON_SetText(hItem, "N");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_M);
    		  BUTTON_SetText(hItem, "M");

    		  qwerty_state=0;

    	  }
        // USER END
        break;
      }
      break;
    case ID_BUTTON_SYM: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
    	  if(qwerty_state!=2)
    	  {
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Q);
    		  BUTTON_SetText(hItem, "+");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_W);
    		  BUTTON_SetText(hItem, "x");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_E);
    		  BUTTON_SetText(hItem, "/");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_R);
    		  BUTTON_SetText(hItem, "=");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_T);
    		  BUTTON_SetText(hItem, "%");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Y);
    		  BUTTON_SetText(hItem, "_");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_U);
    		  BUTTON_SetText(hItem, "*");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_I);
    		  BUTTON_SetText(hItem, "^");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_O);
    		  BUTTON_SetText(hItem, "(");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_P);
    		  BUTTON_SetText(hItem, ")");

    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_A);
    		  BUTTON_SetText(hItem, "!");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_S);
    		  BUTTON_SetText(hItem, "@");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_D);
    		  BUTTON_SetText(hItem, "#");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_F);
    		  BUTTON_SetText(hItem, "&");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_G);
    		  BUTTON_SetText(hItem, "-");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_H);
    		  BUTTON_SetText(hItem, "'");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_J);
    		  BUTTON_SetText(hItem, "\"");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_K);
    		  BUTTON_SetText(hItem, "?");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_L);
    		  BUTTON_SetText(hItem, "~");

    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Z);
    		  BUTTON_SetText(hItem, ">");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_X);
    		  BUTTON_SetText(hItem, "<");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_C);
    		  BUTTON_SetText(hItem, "\\");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_V);
    		  BUTTON_SetText(hItem, "|");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_B);
    		  BUTTON_SetText(hItem, ":");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_N);
    		  BUTTON_SetText(hItem, ";");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_M);
    		  BUTTON_SetText(hItem, "$");

    		  qwerty_state=2;

    	  }
    	  else
    	  {
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Q);
    		  BUTTON_SetText(hItem, "Q");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_W);
    		  BUTTON_SetText(hItem, "W");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_E);
    		  BUTTON_SetText(hItem, "E");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_R);
    		  BUTTON_SetText(hItem, "R");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_T);
    		  BUTTON_SetText(hItem, "T");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Y);
    		  BUTTON_SetText(hItem, "Y");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_U);
    		  BUTTON_SetText(hItem, "U");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_I);
    		  BUTTON_SetText(hItem, "I");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_O);
    		  BUTTON_SetText(hItem, "O");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_P);
    		  BUTTON_SetText(hItem, "P");

    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_A);
    		  BUTTON_SetText(hItem, "A");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_S);
    		  BUTTON_SetText(hItem, "S");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_D);
    		  BUTTON_SetText(hItem, "D");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_F);
    		  BUTTON_SetText(hItem, "F");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_G);
    		  BUTTON_SetText(hItem, "G");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_H);
    		  BUTTON_SetText(hItem, "H");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_J);
    		  BUTTON_SetText(hItem, "J");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_K);
    		  BUTTON_SetText(hItem, "K");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_L);
    		  BUTTON_SetText(hItem, "L");

    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Z);
    		  BUTTON_SetText(hItem, "Z");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_X);
    		  BUTTON_SetText(hItem, "X");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_C);
    		  BUTTON_SetText(hItem, "C");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_V);
    		  BUTTON_SetText(hItem, "V");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_B);
    		  BUTTON_SetText(hItem, "B");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_N);
    		  BUTTON_SetText(hItem, "N");
    		  hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_M);
    		  BUTTON_SetText(hItem, "M");

    		  qwerty_state=0;

    	  }
        // USER END
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:

    	if(cursor<255)
        {
    		message[cursor]='1';
    		cursor++;
        }
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:

    	if(cursor<255)
        {
    		message[cursor]='2';
    		cursor++;
        }
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:

    	if(cursor<255)
        {
    		message[cursor]='3';
    		cursor++;
        }
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;

    case ID_BUTTON_4: // Notifications sent by '4'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:

    	if(cursor<255)
        {
    		message[cursor]='4';
    		cursor++;
        }
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_BUTTON_5: // Notifications sent by '5'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:

    	if(cursor<255)
        {
    		message[cursor]='5';
    		cursor++;
        }
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_BUTTON_6: // Notifications sent by '6'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:

    	if(cursor<255)
        {
    		message[cursor]='6';
    		cursor++;
        }
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;


  case ID_BUTTON_7: // Notifications sent by '7'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		message[cursor]='7';
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_8: // Notifications sent by '8'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		message[cursor]='8';
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_9: // Notifications sent by '9'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		message[cursor]='9';
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_0: // Notifications sent by '0'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		message[cursor]='0';
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_ENTER: // Notifications sent by 'ENTER'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		message[cursor]=10;
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_SPACE: // Notifications sent by 'SPACE'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		message[cursor]=' ';
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;

  case ID_BUTTON_DEL: // Notifications sent by 'DEL'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor>0)
      {
  		cursor--;
  		message[cursor]=0;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_COMMA: // Notifications sent by 'COMMA'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

      	if(cursor<255)
          {
      		message[cursor]=',';
      		cursor++;
          }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;

    break;

  case ID_BUTTON_DOT: // Notifications sent by 'DOT'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		message[cursor]='.';
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;

  case ID_BUTTON_Q: // Notifications sent by 'Q'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='Q';
  					break;
  			case 1: message[cursor]='q';
  					break;
  			case 2: message[cursor]='+';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_W: // Notifications sent by 'W'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='W';
  					break;
  			case 1: message[cursor]='w';
  					break;
  			case 2: message[cursor]='x';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_E: // Notifications sent by 'E'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='E';
  					break;
  			case 1: message[cursor]='e';
  					break;
  			case 2: message[cursor]='/';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_R: // Notifications sent by 'R'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='R';
  					break;
  			case 1: message[cursor]='r';
  					break;
  			case 2: message[cursor]='=';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_T: // Notifications sent by 'T'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='T';
  					break;
  			case 1: message[cursor]='t';
  					break;
  			case 2: message[cursor]='%';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_Y: // Notifications sent by 'Y'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='Y';
  					break;
  			case 1: message[cursor]='y';
  					break;
  			case 2: message[cursor]='_';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_U: // Notifications sent by 'U'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='U';
  					break;
  			case 1: message[cursor]='u';
  					break;
  			case 2: message[cursor]='*';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_I: // Notifications sent by 'I'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='I';
  					break;
  			case 1: message[cursor]='i';
  					break;
  			case 2: message[cursor]='^';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_O: // Notifications sent by 'O'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='O';
  					break;
  			case 1: message[cursor]='o';
  					break;
  			case 2: message[cursor]='(';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_P: // Notifications sent by 'P'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='P';
  					break;
  			case 1: message[cursor]='p';
  					break;
  			case 2: message[cursor]=')';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_A: // Notifications sent by 'A'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='A';
  					break;
  			case 1: message[cursor]='a';
  					break;
  			case 2: message[cursor]='!';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_S: // Notifications sent by 'S'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='S';
  					break;
  			case 1: message[cursor]='s';
  					break;
  			case 2: message[cursor]='@';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_D: // Notifications sent by 'D'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='D';
  					break;
  			case 1: message[cursor]='d';
  					break;
  			case 2: message[cursor]='#';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_F: // Notifications sent by 'F'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='F';
  					break;
  			case 1: message[cursor]='f';
  					break;
  			case 2: message[cursor]='&';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_G: // Notifications sent by 'G'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='G';
  					break;
  			case 1: message[cursor]='g';
  					break;
  			case 2: message[cursor]='-';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_H: // Notifications sent by 'H'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='H';
  					break;
  			case 1: message[cursor]='h';
  					break;
  			case 2: message[cursor]='\'';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_J: // Notifications sent by 'J'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='J';
  					break;
  			case 1: message[cursor]='j';
  					break;
  			case 2: message[cursor]='"';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_K: // Notifications sent by 'K'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='K';
  					break;
  			case 1: message[cursor]='k';
  					break;
  			case 2: message[cursor]='?';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_L: // Notifications sent by 'L'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='L';
  					break;
  			case 1: message[cursor]='l';
  					break;
  			case 2: message[cursor]='~';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_Z: // Notifications sent by 'Z'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='Z';
  					break;
  			case 1: message[cursor]='z';
  					break;
  			case 2: message[cursor]='>';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_X: // Notifications sent by 'X'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='X';
  					break;
  			case 1: message[cursor]='x';
  					break;
  			case 2: message[cursor]='<';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_C: // Notifications sent by 'C'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='C';
  					break;
  			case 1: message[cursor]='c';
  					break;
  			case 2: message[cursor]='\\';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_V: // Notifications sent by 'V'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='V';
  					break;
  			case 1: message[cursor]='v';
  					break;
  			case 2: message[cursor]='|';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_B: // Notifications sent by 'B'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='B';
  					break;
  			case 1: message[cursor]='b';
  					break;
  			case 2: message[cursor]=':';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;


  case ID_BUTTON_N: // Notifications sent by 'N'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='N';
  					break;
  			case 1: message[cursor]='n';
  					break;
  			case 2: message[cursor]=';';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;
  case ID_BUTTON_M: // Notifications sent by 'M'
    switch(NCode) {
    case WM_NOTIFICATION_CLICKED:

  	if(cursor<255)
      {
  		switch(qwerty_state)
  		{
  			case 0: message[cursor]='M';
  					break;
  			case 1: message[cursor]='m';
  					break;
  			case 2: message[cursor]='$';
  					break;
  		}
  		cursor++;
      }
      // USER START (Optionally insert code for reacting on notification message)
      // USER END
      break;
    }
    break;



  // USER START (Optionally insert additional message handling)
  // USER END
  }
  break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateQWERTY
*/
WM_HWIN CreateQWERTY(void);
WM_HWIN CreateQWERTY(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
